### DISCUSSION TITLE
Can't change path of generated models go in locally project

### DISCUSSION THREAD

**Discussion by 0xByteLeon** [99designs/gqlgen#1794] [Q&A]
### What happened?
local project can't set Where should any generated models go

If I change path of generated models go to not default path and run `go run github.com/99designs/gqlgen`, there is a error: no required module provides package `set path`

This is my config file of gqlgen
```
# Where are all the schema files located? globs are supported eg  src/**/*.graphqls
schema:
  - schema/*.graphqls
  - schema/*.graphql

# Where should the generated server code go?
exec:
  filename: pkg/generated/generated.go
  package: generated

# Uncomment to enable federation
# federation:
#   filename: graph/generated/federation.go
#   package: generated

# Where should any generated models go?
model:
  filename: pkg/model/models_gen.go
  package: model

# Where should the resolver implementations go?
resolver:
  layout: follow-schema
  dir: pkg/resolver
  package: resolver
  filename_template: "{name}.go"

# Optional: turn on use `gqlgen:"fieldName"` tags in your models
# struct_tag: json

# Optional: turn on to use []Thing instead of []*Thing
# omit_slice_element_pointers: false

# Optional: set to speed up generation time by not performing a final validation pass.
# skip_validation: true

# gqlgen will search for any type names in the schema in these go packages
# if they match it will use them, otherwise it will generate them.
autobind:
  - "github.com/leon/gqlgen-todos/graph/model"

# This section declares type mapping between the GraphQL and go type systems
#
# The first line in each type will be used as defaults for resolver arguments and
# modelgen, the others will be allowed when binding to fields. Configure them to
# your liking
models:
  ID:
    model:
      - github.com/99designs/gqlgen/graphql.ID
      - github.com/99designs/gqlgen/graphql.Int
      - github.com/99designs/gqlgen/graphql.Int64
      - github.com/99designs/gqlgen/graphql.Int32
  Int:
    model:
      - github.com/99designs/gqlgen/graphql.Int
      - github.com/99designs/gqlgen/graphql.Int64
      - github.com/99designs/gqlgen/graphql.Int32

```

### What did you expect?
local project can config file name of models go 

### Minimal graphql.schema and models to reproduce

- schema.graphqls
```
type Query {
  todos: [Todo!]!
}

type Mutation {
  createTodo(input: NewTodo!): Todo!
}
```
- user.graphql
```
type User {
    id: ID!
    name: String!
}

extend type Query {
    queryTodosByUserID(userID:String!):[Todo!]!
}

extend type Mutation {
    register(userName:String!):User!
}
```
- todo.graphql
```
type Todo {
    id: ID!
    text: String!
    done: Boolean!
    user: User!
}

input NewTodo {
    text: String!
    userId: String!
}
```
### versions
 - `gqlgen version`?  v0.13.0
 - `go version`? v1.16.3
 - dep or go modules? 

```
go 1.16
require (
	github.com/99designs/gqlgen v0.13.0 // indirect
	github.com/google/uuid v1.2.0 // indirect
	github.com/vektah/gqlparser/v2 v2.1.0 // indirect
)

```
