### DISCUSSION TITLE
autobind is not working

### DISCUSSION THREAD

**Discussion by qhenkart** [99designs/gqlgen#1826] [Q&A]
I am sure this must be something I am doing wrong. If you have any suggestions on how I can debug or where to look in the generation package, I will investigate further

### What happened?
autobind works for many of my explicitly defined models, on the most recent one, it fails

```
validation failed: packages.Load: .../generated.go:1507:6: PostInput redeclared in this block
.../posts.go:512:6: 	other declaration of PostInput
exit status 1
resolver/resolver.go:3: running "go": exit status 1
```

### What did you expect?

I expected generation to not generate a model that already exists

### Minimal graphql.schema and models to reproduce

I cannot reproduce this. It seems completely random that this particular model didn't work. It represents an input type, but I have other input types bound as well. I am happy to investigate further with some guidance on where to start looking

```
schema:
 - schema/**/*.graphql
 - schema/*.graphql

exec:
  filename: graph/generated/generated.go
  package: generated

resolver:
  filename: resolver/resolver.go 
  type: Resolver

model:
  filename: models/generated.go
  package: models

struct_tag: json

autobind:
  - "..path/to/project/models"

models:
  Timestamp:
    model:..path/to/project/utils.Timestamp
  ErrInfo:
    model: ..path/to/project/utils.ErrInfo    
```

I also tried directly binding the model in the same way as Timestamp, but the same error occurred 

### versions
 - `gqlgen version`11
 - `go version`? 1.14
 - dep or go modules? mod
