### DISCUSSION TITLE
/../../../models.go:xx adding resolver method for <existing resolver>, nothing matched

### DISCUSSION THREAD

**Discussion by qhenkart** [99designs/gqlgen#1909] [Q&A]
### What happened?
When using the modelgen plugin, Generator returns a lot of errors, generates models properly but does not generate resolvers

I copy and paste the code directly from here and even simplify the hook so it does nothing
https://gqlgen.com/recipes/modelgen-hook/

```
// Defining mutation function
func mutateHook(b *modelgen.ModelBuild) *modelgen.ModelBuild {
	return b
}
```

Running generate creates hundreds of errors following the example in the title for every single resolver I have 
/../../../models.go:xx adding resolver method for <existing resolver>, nothing matched
/../../../models.go:xx adding resolver method for <existing resolver>, nothing matched
/../../../models.go:xx adding resolver method for <existing resolver>, nothing matched
/../../../models.go:xx adding resolver method for <existing resolver>, nothing matched

nothing actually happens with those errors though. No resolver method is actually added. In fact if I add new resolvers,. I need to add them manually, the generator seems to break.

Removing the plugin generates properly

### What did you expect?
For the generator to function as normal and generate resolvers without noisy errors

### Minimal graphql.schema and models to reproduce
```
schema:
  - schema/*.graphqls

exec:
  filename: graph/generated/generated.go
  package: generated

model:
  filename: graph/models/models_gen.go
  package: models

resolver:
  layout: follow-schema
  dir: graph/resolvers
  package: resolvers
  filename_template: "{name}.resolvers.go"
    
autobind:
  - "github.com/xx/xx/graph/models"

```

### versions
 - `gqlgen version` 1.14? 
 - `go version` 1.16?
 - dep or go modules? go mod
