### DISCUSSION TITLE
Breaking out resolvers into packages

### DISCUSSION THREAD

**Discussion by bofia** [99designs/gqlgen#1938] [Q&A]
### What happened?
When running `gqlgen` all the generated resolvers are in a single package. How would you organize a large project that has hundreds of different types? It seems like the package would have hundreds of files in the same directory.

### What did you expect?
A way to organize large schemas. Federation might be a solution but would like to avoid that

### versions
 - `gqlgen version`? v0.11.3
 - `go version`? 1.13.7
 - dep or go modules? N/A

**Comment by qhenkart** [comment]
@bofia actually you don't need gqlgen to support this feature. You can easily do this with Golang's native type extension. With this, I have developed several unique query resolvers types, as well as delegated a separate package to handle mutations which also has unique mutation resolver types

First I will showcase how to use multiple types to organize your code, second I will show you how to use multiple packages.

In your main resolver.go file you will have type set like this 

**resolvers/resolver.go**
```
type Resolver struct{}
type queryResolver struct{ *Resolver }

// Query returns the query resolver
func (r *Resolver) Query() generated.QueryResolver {
	return &queryResolver{r}
}

func (r *Resolver) User() generated.UserResolver {
	return &userResolver{r}
}
```

**resolvers/users.go**
```
_root resolvers must be a part of the queryResolver_
func (r *queryResolver) User(ctx context.Context, id string) (*models.User, error) {
  return nil, nil 
}

 _subresolvers of the root resolver can be a part of the sub class we've created_
type userResolver struct{ *Resolver }

func (r *userResolver) Posts (ctx context.Context) {*models.PostResponse, error} {
  return nil, nil
}

```

So that is a way to at least separate the types you are dealing with which makes testing and code organization much easier. However I did not yet answer your question about using different packages. Using different packages uses the exact same concept as above but we are delegating the class extension to another package. In this example, we are doing it for mutations

**resolvers/resolver.go**
```
type mutationResolver struct {
	*mutations.Resolver
}

// notice here we are calling a packageName.Resolver
func (r *Resolver) Mutation() generated.MutationResolver {
	return &mutationResolver{&mutations.Resolver{}}
}
```

**/resolvers/mutations/mutations.go**
```
package mutations

// Resolver defines the mutation resolver
type Resolver struct{}

func (r *Resolver) CreateUser(ctx context.Context, input models.CreateUserInput) (*models.User, error) {
    return nil, nil 
}
```

Using subclassing, you can easily organize your code into as many packages you want, and create any system that makes the most sense for your use case

**Comment by bofia** [comment]
@qhenkart Thanks for the pointer! I followed your mutation example, however when I run `gqlgen generate`, it will revert back to the one package assumption. E.g. a `resolver/mutation.resolvers.go` will get generated to look like this:

```go
package resolver

func (r *mutationResolver) TestMutate(ctx context.Context, foo *string) (*string, error) {
	panic(fmt.Errorf("not implemented"))
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }

```

even though I already implemented everything needed in `resolver/resolver.go`

**Comment by qhenkart** [comment]
@bofia would you mind sharing your gqlgen.yaml file? I'm not familiar enough with the options to spot the issue off the top of my head

**Comment by bofia** [comment]
@qhenkart Sure, it's mostly the starting template

```yml
# Where are all the schema files located? globs are supported eg  src/**/*.graphqls
schema:
  - graph/schema/**/*.graphqls

# Where should the generated server code go?
exec:
  filename: graph/generated/generated.go
  package: generated

# Uncomment to enable federation
# federation:
#   filename: graph/generated/federation.go
#   package: generated

# Where should any generated models go?
model:
  filename: graph/model/models_gen.go
  package: model

# Where should the resolver implementations go?
resolver:
  layout: follow-schema
  dir: graph/resolver
  package: resolver

# Optional: turn on use `gqlgen:"fieldName"` tags in your models
# struct_tag: json

# Optional: turn on to use []Thing instead of []*Thing
# omit_slice_element_pointers: false

# Optional: set to speed up generation time by not performing a final validation pass.
# skip_validation: true

# gqlgen will search for any type names in the schema in these go packages
# if they match it will use them, otherwise it will generate them.
autobind:
  - "<my private repo>/gqlgen-poc/internal/graph/model"

# This section declares type mapping between the GraphQL and go type systems
#
# The first line in each type will be used as defaults for resolver arguments and
# modelgen, the others will be allowed when binding to fields. Configure them to
# your liking
models:
  ID:
    model:
      - github.com/99designs/gqlgen/graphql.ID
      - github.com/99designs/gqlgen/graphql.Int
      - github.com/99designs/gqlgen/graphql.Int64
      - github.com/99designs/gqlgen/graphql.Int32
  Int:
    model:
      - github.com/99designs/gqlgen/graphql.Int
      - github.com/99designs/gqlgen/graphql.Int64
      - github.com/99designs/gqlgen/graphql.Int32

```
