### DISCUSSION TITLE
gqlgen not generating resolvers from custom model

### DISCUSSION THREAD

**Discussion by alexalexyang** [99designs/gqlgen#2144] [Q&A]
### What happened?

I'm trying out the gqlgen [getting-started tutorial](https://gqlgen.com/getting-started/) and I'm stuck at the section "[Don’t eagerly fetch the user](https://gqlgen.com/getting-started/#dont-eagerly-fetch-the-user)", where we create a custom model and use `go run github.com/99designs/gqlgen generate` to generate new resolvers. But the resolvers were not generated.

### What did you expect?

It looks like this should be generated in graph/schema.resolvers.go:

```
func (r *todoResolver) User(ctx context.Context, obj *model.Todo) (*model.User, error) {
	return &model.User{ID: obj.UserID, Name: "user " + obj.UserID}, nil
}
```

### What did you try?

I found this [comment](https://github.com/99designs/gqlgen/issues/350#issuecomment-423073525) saying we should add to `resolver: true` for the model in gqlgen.yml.

And also this [issue](https://github.com/99designs/gqlgen/issues/658) for the same problem, which led me to its OP's [repo](https://github.com/ShawnRong/bento/blob/master/gqlgen.yml) where he solved the problem with a similar pattern.

So I tried different variations of both, one of them like this:

```
models:
  ...
  Todo:
    model: gqlgen_tutorial/graph/models.Todo
    fields:
      ID:
        resolver: true
```

### Minimal graphql.schema and models to reproduce

graph/model/todo.go
```
package model

type Todo struct {
	ID     string `json:"id"`
	Text   string `json:"text"`
	Done   bool   `json:"done"`
	User   *User  `json:"user"`
}
```

gqlgen.yml:
```
schema:
  - graph/*.graphqls

exec:
  filename: graph/generated/generated.go
  package: generated

model:
  filename: graph/model/models_gen.go
  package: model

resolver:
  layout: follow-schema
  dir: graph
  package: graph
  filename_template: "{name}.resolvers.go"

autobind:
  - "gqlgen_tutorial/graph/model"

models:
  ...
  Todo:
    model: gqlgen_tutorial/graph/model.Todo
    fields:
      ID:
        resolver: true
```

### versions
 - gqlgen v0.17.5
 - go version go1.18.1 darwin/amd64
