### DISCUSSION TITLE
Schema Stitching with Relationships

### DISCUSSION THREAD

**Discussion by mechadragon01** [99designs/gqlgen#2213] [Q&A]
### What happened?
How to properly schema stitch with relationships.
### What did you expect?
Be able to generate without errors.
In `resolvers` directory have:
```
auth.go
resolver.go
user.go
```
### Minimal graphql.schema and models to reproduce
`schema.graphql` blank `Query` and `Mutation` will `extend` in other files
```
scalar Time

type Query {}

type Mutation {}
```

`user.graphql`
```
type User {
  id: ID!
  username: String!
  email: String!
  createdAt: Time!
}

extend type Query {
  me: User
}
```
`type User` is dependent on `scalar Time`, but `scalar Time` is in `schema.graphql`

`auth.graphql`
```
type AuthResponse {
  accessToken: String!
  user: User!
}
```
` type AuthResponse` is dependent on type `User`, but `User` is in `user.graphql`

My `gqlgen.yml` is all set, but can't generate once I split the schema up.
```
schema:
  - graphql/*.graphql

resolver:
  layout: follow-schema
  dir: resolvers
  package: resolvers
  filename_template: "{name}.go"
```

### versions
 - `github.com/99designs/gqlgen v0.17.8`?=
 - `go 1.18`
