### ISSUE TITLE
No resolvers for sub types?

### ISSUE THREAD

**Issue by andremussche** [99designs/gqlgen#1002]
I added some sub types to the todo example.
I expected to get a resolver per sub type. However, I only get a resolver for the query and the first subtype, not for deeper subtypes.

For example, this schema only creates 2 resolvers (for todo and sub) but not for Next2 or More3:
  type MyQueryResolver interface {
  	Todo(ctx context.Context, id int) (*Todo, error)
  }
  type TodoResolver interface {
	Sub(ctx context.Context, obj *Todo) (*Sub, error)
  }

gqlgen version = v0.10.2-dev
go version = go1.13.1 windows/amd64

Schema:
==================
schema {
    query: MyQuery
}

type MyQuery {
    todo(id: ID!): Todo
}

type Todo {
    id: ID!
    text: String!
    done: Boolean! 
    sub: Sub!
}

type Sub {
    id: ID!
    text: String!
    next2: Next2
}

type Next2 {
    id: ID!
    text: String!
    more: More3
}

type More3 {
    id: ID!
    text: String!
}

**Comment by MattJBrowning** [comment]
I believe that is the expected result since it's generating the types. 

If you want to generate a resolver for the sub-types you'll have to either pull the types out and not let gqlgen generate then (this is what I do) or you let gqlgen generate the types and you specify in the config for which fields to force generate a resolver for.

In your case you'd do something similar in your config.
```
models:
  Sub:
    fields:
      next2:
        resolver: true # force a resolver to be generated
  Next2:
    fields:
      more:
        resolver: true # force a resolver to be generated
```
