### ISSUE TITLE
Query results based on subfields filtering

### ISSUE THREAD

**Issue by neelofer-appdirect** [99designs/gqlgen#1049]
### What happened?
We would like to get query results based on a subfield argument.  I have a type schema as defined below. I want to be able to query in the way given below to get list of organisations with list of companies and offices in that organisation only if that office is at a location passed in the query.

I have read related issues and GraphQL notes. But have not been able to get a clear implementation idea for achieving this.

### What did you expect?
Best practice way to query using GraphQL. If we use query arguments, how to and where to use those arguments for sub-fields (in this example office)? 

We are using GORM, with pre-loading. So without the argument, our query works just fine. This is our resolver code right now. We are not explicitly querying for `office` anywhere. We get everything as part of pre-loading. So not sure how to filter sub queries, other than writing a SQL query ourselves (which I want to avoid if this can be done in graphql). 
```
        tx = db.PreloadOrg() // for preloading please refer: http://jinzhu.me/gorm/crud.html#preloading-eager-loading
	var orgs []*Org
	if err := tx.Where(q).Find(&orgs).Error; err != nil {. // at some point, we will read from cache instead of DB
		return nil, LogError(err)
	}
        return orgs, nil
```
Yes we do want to fetch every field, because eventually we want resolver to get data from a cache map, instead of DB. Hence a graphQL feature to achieve this would help us migrate to cache source from DB source.

### Minimal graphql.schema and models to reproduce
Schema:
```
type Org {
  id: Int!
  name: String!
  companies: [Company!]!
}
type Company {
  id: Int!
  name: String!
  offices: [Office!]!
}
type Office {
  id: Int!
  name: String!
  city: String!
  country: String!
}
```

Query to get list of all offices with given query structure where the office is in given city name. If a company does not have an office in given city, then it should be omitted from result. Likewise if an organisation does not have any company office in given city, then the organisation should also be excluded from the results.
```
query {
  orgs {
      companies {
         offices (city: <given city>) {
             name
         }
      }
  }
}
```

### versions
 - `gqlgen version`? v0.10.2
 - `go version`?  go1.13.5
 - dep or go modules? go modules

**Comment by neelofer-appdirect** [comment]
I was able to figure this out. Not using nested resolvers, but using object resolver by improving our model definition.  Hence closing this. Thank you.

**Comment by oliverpool** [comment]
> using object resolver by improving our model definition

@neelofer-appdirect I have the same question: could you share some code on how you solved this?

**Comment by neelofer-appdirect** [comment]
Other than the details above in my question, we used the following model definitions:
```
schema:
  - org.graphql
  - company.graphql
  - office.graphql
exec:
  filename: ..../generated.go
  package: generated
model:
  filename: .../models_gen.go
  package: models
resolver:
  type: Resolver
  layout: follow-schema
  dir: .../resolvers

models:
  Org:
    model: github.com/.../entity.Org
  Company:
    model: github.com/.../entity.Company
  Office:
    model: github.com/.../entity.Office
```

In the `github.com/.../entity` package, I added following model definitions:
```
type Org struct {
	Name string
}
type Company struct {
	Name string
}
type Office struct {
	Name string
	City string
	Country string
}
```

Then generate code with gqlgen and fill in the resolver implementation for finding companies within an org, offices within a company. Hope that helps.
