### ISSUE TITLE
Generate a federated schema when no entity has a `@key`

### ISSUE THREAD

**Issue by matthiasfehr** [99designs/gqlgen#1056]
### What happened?
If you generate a federated schema and only have top level entities without one with a `@key`, there's no `_service` field attached to the Query type and therefore the Apollo Gateway isn't able to fetch the schema of it.

### What did you expect?
That there is still a `_service` field attached to the Query type even without specifying a type with the `@key` directive.

I think this issue should have been fixed by https://github.com/99designs/gqlgen/commit/fa884991b5faec01f1ded737a64350d782e3a418 but it seems the new v0.11.0 release broke it again.

### Minimal graphql.schema and models to reproduce
schema.graphql
```graphql
type Hello {
  name: String!
}

type Query {
  hello: Hello!
}
```
gqlgen.yml
```yaml
schema:
  - "test_data/schema.graphql"
exec:
  filename: generated/generated.go
  package: generated
model:
  filename: models/models_gen.go
  package: models
resolver:
  layout: follow-schema
  dir: resolvers
  package: resolvers
federation:
  filename: generated/federated.go
  package: generated
```

### versions
 - `gqlgen version` `v0.11.0` & `v0.11.1
 - `go version` `1.13.6`
