### ISSUE TITLE
[Question] How to access nested fields in model?

### ISSUE THREAD

**Issue by davendu** [99designs/gqlgen#1059]
Here is my schema: 
```graphql
type UserFile {
  ID: String!
  size: Int!
  md5: String!
  sha512: String!
}
```

And here is my model:
```go
type UserFile {
  UUID: string
  Size: int
  Hashes: Hash
}
type Hashes {
  MD5: string
  SHA512: string
}
```

The `gqlgen.yml` is:
```yaml
# other fields like schema and autobind...
models:
  Userfile: repo/models.UserFile
    fields:
      ID:
        fieldName: UUID
```

How can I generate resolvers automatically for `md5` and `sha512` fields? I tried this way, but it does not work as intended:
```yaml
# other fields like schema and autobind...
models:
  UserFile: 
    model: repo/models.UserFile
      fields:
        MD5:
          fieldName: Hashes.MD5
```
After `go generate`:
```
gofmt failed on generated.go: /repo/generated.go:78:4: expected identifier (and 3 more errors)
gofmt failed on resolver_generated.go: /repo/resolver_generated.go:55:35: expected '(', found '.' (and 2 more errors)
```
Here is what happened on `generated.go` line 78:
```go
type ComplexityRoot struct {
//...
    UserFilestruct {
//...
        Hashes.MD5 func(childComplexity int) int
//...
      }
}
```
And on the generated resolver:
```go
type someResolver struct { *Resolver }

func (r *someResolver ) Hashes.MD5(ctx context.Context, obj *models.UserFile) (string, error) {
    panic("not implemented")
}
```

So I'm sure the way I'm writing `gqlgen.yml` is incorrect...any suggestions?

Thanks.
