### ISSUE TITLE
Ids of type int are marshaled as type string in the API

### ISSUE THREAD

**Issue by henrywoody** [99designs/gqlgen#1096]
### What happened?

I followed the instructions under "IDs are strings but I like ints, why cant I have ints?" in the README and the types work fine within the server so that my object ids are ints. However when fetching data through the API, the ids come out as strings.

### What did you expect?

I expected the ids to be ints in the API as well. Is there a way to set this up / am I missing something here?

#### Schema

```
type Post {
    id: ID!
}
```

#### Model

```
type Post struct {
	ID    int    `json:"id"`
}
```

#### gqlgen.yml

And in `gqlgen.yml`:

```
models:
  ID:
    model:
      - github.com/99designs/gqlgen/graphql.IntID
      - github.com/99designs/gqlgen/graphql.ID
      # ...
```

#### Playground

Query:

```
query getPost {
  post(id: 1) {
    id,
  }
}
```

Result:

```
{
  "data": {
    "post": {
      "id": "1"
    }
  }
}
```

### versions
 - `gqlgen version`? **0.11.1**
 - `go version`? **1.13**
 - dep or go modules? **Modules**

Also follow up question (can post as a separate issue if necessary): Is there any way to change the naming scheme for ids to use like `Id` and `PostId` instead of `ID` and `PostID`?
