### ISSUE TITLE
Field resolver is depended on another field resolver's data

### ISSUE THREAD

**Issue by shreeharsha-factly** [99designs/gqlgen#1106]
### What happened?
My Schema field resolver is depended on Claims field resolver's data. In Claims field resolver I fetch claims with data loader. I want to use that data fetched from Claims field resolver in Schema resolver but when I do that "Obj" just contains claims (type database Ref's )but not claims data.  In order to use claims data, I am calling claims field resolver. And by doing that I making some extra calls to database.

Claims field resolver 
```
func (r *FactcheckResolver) Claims(ctx context.Context, obj *models.Factcheck) ([]*models.Schemas, error) {
   for _, claim := range obj.Claims {
		allClaimID = append(allClaimID, claim.ID)
	}

	claims, _ := loaders.GetClaimLoader(ctx).LoadAll(allClaimID)
	return claims, nil
}
```
Schema field resolver
```
func (r *FactcheckResolver) Schema(ctx context.Context, obj *models.Factcheck) ([]*models.Schemas, error) {
claims, err := r.Claims(ctx, obj) // calling claims field resolver to get claims data
media, err := r.Claim().Media(ctx, obj) // calling claims field resolver's to get claims field data
}
```
### What did you expect?

I don't why "obj" in schema field resolver doesn't contain claims field data but contains (type database ref).

### Minimal graphql.schema and models to reproduce

schema
```
type Factcheck {
    claims: [Claims!]!
    schema: [Schema!]!
    ... other fields
}

type Claims {
   media: Media!
   ... other fields
}
```
models
 ```
type DatabaseRef struct {
	Ref string `bson:"$ref"`
	ID  string `bson:"$id"`
}

type Factcheck struct {
   Claims          [ ]*DatabaseRef  `bson:"claims"`
   ... other fields
}

type Claims struct {
   media          *DatabaseRef  `bson:"media"`
   ... other fields
}
```
gqlgen.yml
```
models:
   claims:
      model: repo/models.Claims
      fields:
        media:
            resolver: true
   factcheck:
      model: repo/models.Factcheck
         fields:
           claims:
             resolver: true
           schema:
             resolver: true
```

### versions
 - `gqlgen version`? v0.11.0
 - `go version`? v1.13
 - dep or go modules? modules
 -  mongo-driver v1.3.0

Help me to figure out how to use one field resolver's data into another Field resolver.

Thanks in advance.
