### ISSUE TITLE
When regenerate resolvers import is canceled

### ISSUE THREAD

**Issue by andreadragotta** [99designs/gqlgen#1123]
### What happened?

When execute `gqlgen generate` the dataloaders import is deleted from one file but is required within it.  

NOTE: In another file with the same import all works, i don't know why only in that file i have this problem.

### What did you expect?

When execute `qglgen generate` the import it isn't deleted and the gqlgen check not print error.

### Minimal graphql.schema and models to reproduce

The gqlgen.yml file is: (i've excluded the model-schema pair)
```
schema:
  - "graphql/schema/**/*.graphql"

exec:
  filename: graphql/generated/generated.go
  package: generated

model:
  filename: graphql/model/models_gen.go
  package: graphmodel

resolver:
  layout: follow-schema
  dir: graphql
  package: graphql
```

### versions
 - `gqlgen version 0.11.3`
 - `go version 1.13.8`
 - `go modules`

Thank you in advance for the help!
