### ISSUE TITLE
Generate imports wrong package and gives error

### ISSUE THREAD

**Issue by randallmlough** [99designs/gqlgen#1171]
### What happened?
When running `go run github.com/99designs/gqlgen generate` the generated resolver functions imports the wrong package.

if I use the [github.com/pkg/errors](https://github.com/pkg/errors) library in my resolvers and then later on I trigger the `generate` command, gqlgen will remove this import and instead import the standard library's `errors` package.  

**PRE `go run github.com/99designs/gqlgen generate`**
```go
// user.resolvers.go

import (
	"context"
	"github.com/pkg/errors"

	"github.com/foo/bar/app"
)

func (r *queryResolver) Me(ctx context.Context) (*app.User, error) {
	user,err := app.UserFromContext(ctx)
	if err != nil {
		return nil, errors.Wrap(err, "no user in context")
	}
	return user, nil
}
```

**POST `go run github.com/99designs/gqlgen generate`**

```sh
validation failed: packages.Load: /github.com/foo/bar/graph/resolver/user.resolvers.go: Wrap not declared by package errors
```

Updated generated file...
```go
// user.resolvers.go

import (
	"context"
	"errors"

	"github.com/foo/bar/app"
)

func (r *queryResolver) Me(ctx context.Context) (*app.User, error) {
	user,err := app.UserFromContext(ctx)
	if err != nil {
		return nil, errors.Wrap(err, "no user in context")
	}
	return user, nil
}
```

So even though stdlib `errors` pkg doesn't have a `Wrap` function, it will still be added to the import statement rather than using the one that was previously declared `github.com/pkg/errors` followed by reporting that the function is not declared in that package.

**gqlconfig.yml**
```yml
schema:
  - "graph/schema/**/*.graphql"

exec:
  filename: graph/generated/generated.go
  package: generated

resolver:
  layout: follow-schema
  dir: graph/resolver
  package: resolver


struct_tag: gql
omit_slice_element_pointers: true

autobind:
  - github.com/foo/bar/app
```

### What did you expect?
import / use the already declared package rather than attempting to import it's own

### Minimal graphql.schema and models to reproduce
```graphql
# schema/schema.graphql
schema {
    query: Query
    mutation: Mutation
}

type Query

type Mutation

```

```graphql
# schema/types/user.graphql
extend type Query {
    me: User
}
type User {
    id: ID!
    email: String!
    name: String
}
```

### versions
 - `gqlgen version`? v0.11.3
 - `go version`? 1.14
 - dep or go modules? go mod
