### ISSUE TITLE
Resolvers for type definitions of basic types

### ISSUE THREAD

**Issue by patrikeh** [99designs/gqlgen#1184]
If I have something like:

```
type ThingType int

type Thing struct {
    ...
    Type ThingType `json:"type"`
}
```

and in schema.graphql:

```
type Thing {
    ...
    type: Int
}
```

gqlgen generates an unimplemented resolver method for `type`, although I'd just like to have it resolve as any other `int`. Is this configurable somehow?

**Comment by LeonardKoll** [comment]
For people googling: You can configure this in you `gqlgen.yml` in the `models` section.
In the example below I added a resolver for the 'listCount' field in 'Users'.

```
# This section declares type mapping between the GraphQL and go type systems
#
# The first line in each type will be used as defaults for resolver arguments and
# modelgen, the others will be allowed when binding to fields. Configure them to
# your liking
models:
  ID:
    model:
      - github.com/99designs/gqlgen/graphql.ID
      - github.com/99designs/gqlgen/graphql.Int
      - github.com/99designs/gqlgen/graphql.Int64
      - github.com/99designs/gqlgen/graphql.Int32
  Int:
    model:
      - github.com/99designs/gqlgen/graphql.Int
      - github.com/99designs/gqlgen/graphql.Int64
      - github.com/99designs/gqlgen/graphql.Int32
  models:
  ID:
    model:
      - github.com/99designs/gqlgen/graphql.ID
      - github.com/99designs/gqlgen/graphql.Int
      - github.com/99designs/gqlgen/graphql.Int64
      - github.com/99designs/gqlgen/graphql.Int32
  Int:
    model:
      - github.com/99designs/gqlgen/graphql.Int
      - github.com/99designs/gqlgen/graphql.Int64
      - github.com/99designs/gqlgen/graphql.Int32
  User:
    fields:
      listCount:
        resolver: true
```
