### ISSUE TITLE
Follow-schema force recreating generated files with resolvers for GraphQL schema

### ISSUE THREAD

**Issue by rbUUbr** [99designs/gqlgen#1187]
### What happened?
I've generated code for graphql files and added comment in files, then run `go run github.com/99designs/gqlgen generate` one more time and find out, that files were recreated
### What did you expect?
Files will not be recreated if they are already exist
### Minimal graphql.schema and models to reproduce
I have a couple of files. Here is file structure:
<img width="440" alt="image" src="https://user-images.githubusercontent.com/18901132/81564565-9ad62f80-93a0-11ea-86d6-70cbd50d207c.png">

and gqlgen.yml:
```yml
schema:
  - "graph/*.graphql"

exec:
  filename: "graph/generated/gql.go"
  package: gql

resolver:
  layout: follow-schema
  dir: graph

model:
  filename: models/generated.go
autobind: []

```
### versions
 - `gqlgen 0.11` 
 - `1.14`
 - go modules
