### ISSUE TITLE
Binding of lowercase GraphQL type name to Go struct

### ISSUE THREAD

**Issue by tkuhlman** [99designs/gqlgen#1234]
### What happened?
We have some existing GraphQL schema that uses lower cased names and existing Go structs that are upper cased to be exportable. The type with the lower cased name also includes another type in its fields. Autobinding does not automatically match these two but that is easy enough to work around. I have tried both using the goModel directive and by explicit binding in gqlgen.yml. In both of these cases the binding works but some of the generated functions are lowercased and so not exported. Specifically it is a problem with the child resolver.

I get this error `galleryResolver not exported by package generated` with the example code below.

### What did you expect?
I expected generated functions to be uppercased and so exported as they would be if the GraphQL type name was upper cased but then bound to the lowercased GraphQL schema name.

### Minimal graphql.schema and models to reproduce
#### Schema
```
directive @goModel(model: String, models: [String!]) on OBJECT                                                                                                 
    | INPUT_OBJECT                                                                                                                                             
    | SCALAR                                                                                                                                                   
    | ENUM                                                                                                                                                     
    | INTERFACE                                                                                                                                                
    | UNION                                                                                                                                                    
                                                                                                                                                               
type Query {                                                                                                                                                   
  galleries: [gallery!]!                                                                                                                                       
}                                                                                                                                                              
                                                                                                                                                               
type gallery @goModel(model: "tmp/gqlgen-bug/graph/model.Gallery") {                                                                                           
  id: ID!                                                                                                                                                      
  images: [Image]                                                                                                                                              
}                                                                                                                                                              
                                                                                                                                                               
type Image {                                                                                                                                                   
  url: String                                                                                                                                                  
}
```
#### Model
```
type Gallery struct {                                                                                                                                          
  ID     string                                                                                                                                                
  Images []GalleryImage                                                                                                                                        
}                                                                                                                                                              
                                                                                                                                                               
type GalleryImage struct {                                                                                                                                     
  URL string                                                                                                                                                   
}     
```
### versions
 - `gqlgen version` - v0.11.3
 - `go version` - 1.14.3
 - dep or go modules? Go modules

**Comment by lwc** [comment]
Generated go types are indeed uppercased and exported correctly. I think you might have an issue in either `graph/resolver.go`  or `graph/schema.resolvers.go`. I have your schema working with the following:

```go
// $ cat graph/resolver.go
package graph

// This file will not be regenerated automatically.
//
// It serves as dependency injection for your app, add any dependencies you require here.

type Resolver struct{}
```
And
```go
// $ cat graph/schema.resolvers.go
package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.

import (
	"context"
	"fmt"

	"github.com/lwc/gqlgen-1234/graph/generated"
	"github.com/lwc/gqlgen-1234/graph/model"
)

func (r *queryResolver) Galleries(ctx context.Context) ([]*model.Gallery, error) {
	panic(fmt.Errorf("not implemented"))
}

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
```

**Comment by tkuhlman** [comment]
My graph/resolver.go was the same as yours above, my schema.resolvers.go was very similar with two additions these lines.
```                                                                                                                                                               
func (r *galleryResolver) Images(ctx context.Context, obj *model.Gallery) ([]*model.Image, error) {
  panic(fmt.Errorf("not implemented"))
}

// gallery returns generated.galleryResolver implementation.
func (r *Resolver) gallery() generated.galleryResolver { return &galleryResolver{r} }
                                                                                                                
type galleryResolver struct{ *Resolver }
```
This was all autogenerated for me by gqlgen, I have not modified it at all.
What isn't clear to me is why your setup seems not to have created an Images resolver? For this simple example it seems like the Images resolver could be completely autogenerated but in my setup it isn't in the generated code. Even if you can explain why it isn't generated for you but is for me perhaps for this example it would be worth forcing it to generate to demonstrate the bug.

For reference here is the gqlgen.yml I am using
```
# Where are all the schema files located? globs are supported eg  src/**/*.graphqls
schema:
  - graph/*.graphqls

# Where should the generated server code go?
exec:
  filename: graph/generated/generated.go
  package: generated

# Uncomment to enable federation
# federation:
#   filename: graph/generated/federation.go
#   package: generated

# Where should any generated models go?
model:
  filename: graph/model/models_gen.go
  package: model

# Where should the resolver implementations go?
resolver:
  layout: follow-schema
  dir: graph
  package: graph

# Optional: turn on use `gqlgen:"fieldName"` tags in your models
# struct_tag: json

# Optional: turn on to use []Thing instead of []*Thing
# omit_slice_element_pointers: false

# Optional: set to speed up generation time by not performing a final validation pass.
# skip_validation: true

# gqlgen will search for any type names in the schema in these go packages
# if they match it will use them, otherwise it will generate them.
autobind:
  - "tmp/gqlgen-bug/graph/model"

# This section declares type mapping between the GraphQL and go type systems
#
# The first line in each type will be used as defaults for resolver arguments and
# modelgen, the others will be allowed when binding to fields. Configure them to
# your liking
models:
  ID:
    model:
      - github.com/99designs/gqlgen/graphql.ID
      - github.com/99designs/gqlgen/graphql.Int
      - github.com/99designs/gqlgen/graphql.Int64
      - github.com/99designs/gqlgen/graphql.Int32
  Int:
    model:
      - github.com/99designs/gqlgen/graphql.Int
      - github.com/99designs/gqlgen/graphql.Int64
      - github.com/99designs/gqlgen/graphql.Int32
```
