### ISSUE TITLE
Could not read from remote repository

### ISSUE THREAD

**Issue by warent** [99designs/gqlgen#1240]
### What happened?
Trying to run gqlgen failed
```
$ gqlgen
validation failed: packages.Load: -: git ls-remote -q origin in /Users/koru/go/pkg/mod/cache/vcs/07a976c11485d76e02837635370a07d0499b63b941f52acb1375ae6304383432: exit status 128:
	ERROR: Repository not found.
	fatal: Could not read from remote repository.

	Please make sure you have the correct access rights
	and the repository exists.
```

### What did you expect?
Should work properly.

Here is the gqlgen.yml

```
schema:
  - graphql/schema.gql

exec:
  filename: internal/graph/server/server.go
  package: gqlserver

model:
  filename: internal/graph/model/model.go
  package: gqlmodel

resolver:
  layout: follow-schema
  dir: internal/graph
  package: gql

autobind:
  - "github.com/your/app/graph/model"

# This section declares type mapping between the GraphQL and go type systems
#
# The first line in each type will be used as defaults for resolver arguments and
# modelgen, the others will be allowed when binding to fields. Configure them to
# your liking
models:
  ID:
    model:
      - github.com/99designs/gqlgen/graphql.ID
      - github.com/99designs/gqlgen/graphql.Int
      - github.com/99designs/gqlgen/graphql.Int64
      - github.com/99designs/gqlgen/graphql.Int32
  Int:
    model:
      - github.com/99designs/gqlgen/graphql.Int
      - github.com/99designs/gqlgen/graphql.Int64
      - github.com/99designs/gqlgen/graphql.Int32
```

### versions
 - `gqlgen version`? 
0.11.3
 - `go version`?
1.13.8
 - dep or go modules?
go mod
