### ISSUE TITLE
[Proposal] Customized json tag key in generated models

### ISSUE THREAD

**Issue by zdunecki** [99designs/gqlgen#1254]
### What happened?
I would like to get a customized JSON tag key in generated models.

### What did you expect?
```go
type Model struct {
  UserID string `json:"user_id"` // or any other format you would like to
}
```

### Proposal
1) via command line:
```bash
go run github.com/99designs/gqlgen generate --json-tag snakecase
```

2) via gqlgen.yml with simple model key:
```yml
model:
  filename: graph/model/models_gen.go
  package: model
  json_tag: snakecase
```

3) via gqlgen.yml with options key:
```yml
model:
  filename: graph/model/models_gen.go
  package: model
  options:
    json_tag: snakecase
```

4) via gqlgen.yml with custom mutate hooks:
```yml
model:
  filename: graph/model/models_gen.go
  package: model
  mutate_hooks:
    - github.com/99designs/gqlgen/plugin/modelgen.SnakeCaseMutateHook
```

* solution 1) and 2) looks simple but is limited. 
* solution 3) looks more customized and it extends `PackageConfig` struct.
* solution 4) is inspired by https://gqlgen.com/recipes/modelgen-hook/ but instead of using API we're invoking hooks via gqlgen.yml but I'm not quite sure if it is possible to invoke function this way.

### Current status 
I'm using `Modelgen hook` to this achieve this but I need separate `.go` file with boilerplate I think that it would be nice to have this feature in a native way.

Similar issue: https://github.com/99designs/gqlgen/issues/824
