### ISSUE TITLE
Improve docs about configuration

### ISSUE THREAD

**Issue by mrdulin** [99designs/gqlgen#1279]
Here is piece of `gqlgen.yml`:
```yaml
resolver:
  layout: follow-schema
  dir: graph
  package: graph
```

What does `layout: follow-schema` mean? Is there any other value for this configuration?  Besides, is there any other configuration for `resolver`? Same for other configurations. I didn't find any doc about this.

I got an error:
> failed to load schema: config.resolver: filename must be specified with layout=single-fileexit status 1

So I knew that there is another value for `layout` configuration called `single-file`. What does this mean?

```yml
model:
#  filename: graph/model/models_gen.go
  dir: graph/model
  package: model
```
I try to use `dir` configuration for `model`, but got error:

> unable to parse config: yaml: unmarshal errors:
  line 18: field dir not found in type config.PackageConfigexit status 1

So I knew maybe `dir` configuration should not be used for `model`.
