### ISSUE TITLE
split resolver.go

### ISSUE THREAD

**Issue by liyaqin1** [99designs/gqlgen#1371]
My resolver.go and schema.graphql is very huge.

I want to split these two files especially resolver.go.

Is there a way to do it? Thanks.

**Comment by nzlov** [comment]
`gqlgen.yml`:
```
resolver:
  layout: follow-schema
  dir: graph
  package: graph
```

Split `schema.graphql` and retry generate
