### ISSUE TITLE
Invalid generated code for inputs when go model field type does not match the graphql field type

### ISSUE THREAD

**Issue by danielvladco** [99designs/gqlgen#1403]
Reopen #663

### What happened?
Invalid go code was generated.
### What did you expect?
I expect valid go code to be generated. The actual generated code is not building for the following reason:
`gql/exec.go:2298:17: cannot assign []*proj.MapEntry to it.Map (type map[string]string) in multiple assignment`

This is the generated go code part that is failing:
```go
case "map":
	var err error
	it.Map, err = ec.unmarshalOMapEntry(ctx, v) // failing here
	if err != nil {
		return it, err
	}
```
### Minimal graphql.schema and models to reproduce

--- schema.graphqls
```graphql
type Query {
    foo(in: Bar): Boolean
}

input Bar {
    map: [MapEntry]
}
input MapEntry {
    key: String
    val: String
}
```

--- gqlgen.yaml
```yaml
schema:
- schema.graphqls
exec:
  filename: exec.go
model:
  filename: models.go
models:
  Bar:
    model:
    - github.com/company/proj.Bar
  MapEntry:
    model:
    - github.com/company/proj.MapEntry
```
--- models.go
```go
type Bar struct {
    Map map[string]string
}

type MapEntry struct {
    Key string
    Val string
}
```

I tried the same usecase with graphql `type` and an additional resolver was added that has as parameter `Bar` and returns `MapEntry`.

I am aware of the fact that graphql types and inputs are totally different concepts and why the generated code was broken but I think it would be very handy to have some kind of generated resolvers similar to the ones for the type or some workaround for similar usecases.
Maybe show an error at generation time?
