### ISSUE TITLE
Custom model in the same local app is not loading

### ISSUE THREAD

**Issue by ydeshayes** [99designs/gqlgen#1437]
### What happened?
When trying to use a custom model with the yml file or the directive, it seems that gqlgen want to load that from a remote repo. But my model is just in an other package on the same project.

Error:
```
 git ls-remote -q .... can't read remote repository
```

### What did you expect?

I would expect gqlgen to load the model from my local package.

### Minimal graphql.schema and models to reproduce
gqlgen.yml
```

# This section declares type mapping between the GraphQL and go type systems
#
# The first line in each type will be used as defaults for resolver arguments and
# modelgen, the others will be allowed when binding to fields. Configure them to
# your liking
models:
  ID:
    model:
      - github.com/99designs/gqlgen/graphql.ID
      - github.com/99designs/gqlgen/graphql.Int
      - github.com/99designs/gqlgen/graphql.Int64
      - github.com/99designs/gqlgen/graphql.Int32
  Int:
    model:
      - github.com/99designs/gqlgen/graphql.Int
      - github.com/99designs/gqlgen/graphql.Int64
      - github.com/99designs/gqlgen/graphql.Int32
  User:
    model: go.app.com/a/b/user/store.User
```
```
type User {
  id: String!
  email: String!
  un: String!
}

type Query {
  users: [User!]!
}
```
model in the package go.app.com/a/b/user/store.User
```
type User struct {
	ID string
	Un     string
	EmailAddress string `db:"email"`
}
```

### versions
 - `gqlgen version`? 
 v0.13.0
 - `go version`?
 go version go1.13.8 linux/amd64
 - dep or go modules?
Gin
