### ISSUE TITLE
resolvers filename_template not working

### ISSUE THREAD

**Issue by araufdogan** [99designs/gqlgen#1438]
### What happened?
I want to split resolvers by name.

### What did you expect?
Split query and mutation resolvers by file name. I have two mutations named login and logout, It should generate two resolvers named login_resolvers.go, logout_resolvers.go. (I deleted the single resolver file before trying to generate it)

### gqlgen.yml

```
schema:
  - graphql/*.graphqls

exec:
  filename: graphql/generated/generated.go
  package: generated

model:
  filename: graphql/model/models_gen.go
  package: model

resolver:
  layout: follow-schema
  dir: graphql
  package: graphql
  filename_template: "{name}.resolvers.go"

```
### Minimal graphql.schema and models to reproduce

```
type Mutation {
  login: String
  logout: Boolean
}

```
### versions
 - `gqlgen version`?    v0.13.0
 - `go version`?    go1.14
 - dep or go modules?    go modules
