### ISSUE TITLE
Manual Configuration of mapping go structs to schema types is only possible by defining schema type in Pascal-case

### ISSUE THREAD

**Issue by avi94** [99designs/gqlgen#1580]
### What happened?
So we have a type Item, and looks something like below(notice the camel-case of item type):

```
type item {
    assignmentNumber: String!
    itemNumber: String!
    targetQuantity: String!
    storeLocation: String!
    batch: String!
    conditions: [condition!]!
    balanceQuantity: String!
    balanceValue: String!
}
```

Below is my gqlgen.yml

```
# Where are all the schema files located? globs are supported eg  src/**/*.graphqls
schema:
  - schema.graphql

# Where should the generated server code go?
exec:
  filename: ereturns/generated.go
  package: ereturns

# Uncomment to enable federation
# federation:
#   filename: graph/generated/federation.go
#   package: generated

# Where should any generated models go?
model:
  filename: models/models_gen.go
  package: models

# Where should the resolver implementations go?
resolver:
  #  layout: follow-schema
  #  dir: graph
  filename: ereturns/resolver.go
  package: ereturns
  type: Resolver

# Optional: turn on use `gqlgen:"fieldName"` tags in your models
# struct_tag: json

# Optional: turn on to use []Thing instead of []*Thing
# omit_slice_element_pointers: false

# Optional: set to speed up generation time by not performing a final validation pass.
# skip_validation: true

# gqlgen will search for any type names in the schema in these go packages
# if they match it will use them, otherwise it will generate them.
autobind:
  []
#  - "github.com/JasonSia/ereturns/graph/model"

# This section declares type mapping between the GraphQL and go type systems
#
# The first line in each type will be used as defaults for resolver arguments and
# modelgen, the others will be allowed when binding to fields. Configure them to
# your liking
models:
  Item:
    model: github.com/avixyz/ereturns/models.Item
  ID:
    model:
      - github.com/99designs/gqlgen/graphql.ID
      - github.com/99designs/gqlgen/graphql.Int
      - github.com/99designs/gqlgen/graphql.Int64
      - github.com/99designs/gqlgen/graphql.Int32
  Int:
    model:
      - github.com/99designs/gqlgen/graphql.Int
      - github.com/99designs/gqlgen/graphql.Int64
      - github.com/99designs/gqlgen/graphql.Int32

```

Generating the struct manually by configuring it in the gqlgen.yml file was throwing the common and infamous error "Item redeclared in this block other declaration of Item". I spent hours on it only to discover, not through any docs but instead through trial and error, that the camel case is the issue. Pascal case actually works.

My question is, why doesn't it work for camel case, it should work for camel case. Our entire microservice architecture is written in this camel case style in all our schema files. Providing a screenshot of the structure of a module in the project. 

![image](https://user-images.githubusercontent.com/20141385/128548923-91866699-e6a4-4903-a7f9-3fafbff83f29.png)

### What did you expect?

Camel case to work.

### versions
 - `gqlgen version`?  13.0
 - `go version`? 1.16
 - dep or go modules? go modules
