### ISSUE TITLE
How to Fetch child objects on Union Type 

### ISSUE THREAD

**Issue by liam-lai** [99designs/gqlgen#1611]
### What happened?
I have one property on union type and also would like to have dynamic fetch object only when the actual type is getting query.
Looks for the example and documents, can't see any example on Union type. Not sure if it's supported or not.

### What did you expect?
I am expected something like this syntax and generated each resolver.
```
#schema.graphqls
union Components =
  | Banner
  | Header

type Card {
  type: String
  items: [Components]
}
```
```
#gqlgen.yml
models:
  Card:
    fields:
      items: 
        Banner:
          resolver: true # force a resolver to be generated
        Header:
          resolver: true # force a resolver to be generated
```
### Minimal graphql.schema and models to reproduce

```
#schema.graphqls
union Components =
  | Banner
  | Header

type Card {
  type: String
  items: [Components]
}
```
I can only got items and return the []model.Components, which I still need to prepare all the childs objects.
```
#gqlgen.yml
models:
  Card:
    fields:
      items:
        resolver: true # force a resolver to be generated
```
```
func (r *DataResolver) Items(ctx context.Context, obj *model.Data) ([]model.Components, error) {
	panic(fmt.Errorf("not implemented"))
}
```
### Example Query
```
# Should only fetch Header and Banner Data
{
	Card{
		items{
			... on Header {}
			... on Banner {}
		}
	}
}
# Should only fetch Banner
{
	Card{
		items{
			... on Banner {}
		}
	}
}
# Should only fetch Header
{
	Card{
		items{
			... on Header {}
		}
	}
}
```
### versions
 - `gqlgen version` v0.13.0 
 - `go version` go1.16.6
 - dep or go modules? go modules
