### ISSUE TITLE
Custom Scalar - PostgresQL JSONB Type

### ISSUE THREAD

**Issue by JessedeJonge** [99designs/gqlgen#1758]
Trying to find some good documentation about this but it seems like this has not been documented very well..
Lets say I have a column of type JSONB in PostgresSQL. How would I define this type in our graphql schema? 
Would this best be a custom scalar or use Any. If Any, how does this work? I have tried adding the following to the gqlgen.yaml:

```
models:
  ID:
    model:
      - github.com/99designs/gqlgen/graphql.Int64
  Any:
    model:
      - github.com/99designs/gqlgen/graphql.Any
 ```

But still getting `Undefined type Any`
