### ISSUE TITLE
Enable mapping a GraphQL field to a different model field

### ISSUE THREAD

**Issue by anurag** [99designs/gqlgen#198]
### Expected Behaviour
It'd be nice to be able to map field X in a graphql schema to a different object field via a mapping directive in `gqlgen.yaml`.

### Sample gqlgen.yaml (from https://gqlgen.com/config/)
```yaml
schema: schema.graphql

# Let gqlgen know where to put the generated server
exec:
  filename: graph/generated/generated.go
  package: generated

# Let gqlgen know where to the generated models (if any)
model:
  filename: models/generated.go
  package: models

# Tell gqlgen about any existing models you want to reuse for
# graphql. These normally come from the db or a remote api.
models:
  User:
    model: github.com/my/app/models.User
  Todo:
    model: github.com/my/app/models.Todo
    fields:
      id:
        modelField: IDString # maps to field IDString in models.Todo
```
