### ISSUE TITLE
examples/federation can't generate the correct query resolve codes

### ISSUE THREAD

**Issue by richgrove** [99designs/gqlgen#2137]
### What happened?
Using the 99designs/gqlgen@v0.17.5 and following the instruction at https://gqlgen.com/recipes/federation/, try to create the federation example project.   After enable the federation and update the reviews/graph/schema.graphqls with federated schema as:

```
type Review {
  body: String
  author: User @provides(fields: "username")
  product: Product
}

extend type User @key(fields: "id") {
  id: ID! @external
  reviews: [Review]
}

extend type Product @key(fields: "upc") {
  upc: String! @external
  reviews: [Review]
}
```

Run the generate command as:
`go run github.com/99designs/gqlgen`

It supposes to generate the files:  schema.resolvers.go, entity.resolvers.go, graph/generated/generated/generated.go and federation.go with the updated schema.
Inside the generated.go, it doesn't have 
```
type ResolverRoot interface {
	Entity() EntityResolver
	Product() ProductResolver
	User() UserResolver
}
```
with ProductResolver and UserResolver

### What did you expect?
It should generate the correct resolver codes with the above interface.

### Minimal graphql.schema and models to reproduce
See the above description about the schema.

### versions
 - `go run github.com/99designs/gqlgen version`?
 - `go version`?
I am using the v0.17.5 and go 1.18.    I don't have any problem to run the examples/federation without any changes to query the correct result.

**Comment by lleadbet** [comment]
Hi there! It's not super clear _why_ this is the case in the docs, but is expected. 

`ResolverRoot` defines the entry points for your graph; in non-federated instances, this would just be Mutation, Query, and Subscription; For Federated graphs, they'd also include an Entities endpoint used to resolve subgraph-provided fields. 

A good outline to explain how that works is here: https://www.apollographql.com/docs/federation/entities

The short version is that if there are fields contributed by only one subgraph, the gateway will use an entity resolver to get the entity (in this case, `User`) and then expect to get back the Reviews. The EntityResolver for the User would be sufficient if your service would return a User struct along with the associated Reviews. Now, if your service can't return the value, that's when the additional root resolvers are needed. 

In the example, it uses a pre-formatted Model as shown here: https://github.com/99designs/gqlgen/blob/master/_examples/federation/reviews/graph/model/models.go

Now - if you need a resolver that's specific to a field, you can also follow the above format or using: https://gqlgen.com/#using-explicit-resolvers

**Comment by richgrove** [comment]
I am not asking the specific fields to be coded here.  Can you start a new project for the reviews by using the schema, https://github.com/99designs/gqlgen/blob/master/_examples/federation/reviews/graph/schema.graphqls, to run the "go run github.com/99designs/gqlgen" and get the "expected" schema.resolvers.go and graph/generated/generated.go files.  

I can't get them.  Why is it not able to generate them?   This is what I tried here.   I don't know how the _examples/federation/reviews get those generated codes.  I am not expecting the generated codes to have all implementation, but the function prototypes should have been created.  If not, can you tell how to get them?

As I said, I don't have any problem to compile and run the federation example.  But, I do need to know and understand how to use it to create my project.  I believe this is federation example document wants to teach everybody.  It may work before.  At the current 0.17.5 release, I can't recreate the example result. 

Even, I tried to use federation "version: 2".  It has the same result.  The simple way to help me here is that you follow the document guide to recreate the federation/reviews.

**Comment by lleadbet** [comment]
I believe the docs should be updated; the only changes you'd need to make to get those entities to resolve directly from the example would be updating the `gqlgen.yml` file such that: 

```yml
models:
  # ... after existing imports
  User:
    fields:
      reviews:
        resolver: true
```

And repeating for any other fields you need to generate field-specific resolvers for. Out of the box, you're correct- it's not generating, but the above post explains _why_ that may not be needed in an actual implementation case. 

@frederikhors / @StevenACoffman may have thoughts here as maintainers.

**Comment by richgrove** [comment]
What you mentioned to alter the gqlgen.yml, I can't see that in both
```
https://github.com/99designs/gqlgen/blob/master/_examples/federation/reviews/gqlgen.yml
https://github.com/jensneuse/graphql-go-tools/tree/master/examples/federation/reviews/gqlgen.yml
```
I don't know this is the latest update or not.

**Comment by lleadbet** [comment]
Here's my exact `gqlgen.yml`:

```yml
# Where are all the schema files located? globs are supported eg  src/**/*.graphqls
schema:
  - graph/*.graphqls

# Where should the generated server code go?
exec:
  filename: graph/generated/generated.go
  package: generated

federation:
  filename: graph/generated/federation.go
  package: generated

# Where should any generated models go?
model:
  filename: graph/model/models_gen.go
  package: model

# Where should the resolver implementations go?
resolver:
  layout: follow-schema
  dir: graph
  package: graph

# Optional: turn on use `gqlgen:"fieldName"` tags in your models
# struct_tag: json

# Optional: turn on to use []Thing instead of []*Thing
# omit_slice_element_pointers: false

# Optional: set to speed up generation time by not performing a final validation pass.
# skip_validation: true

# gqlgen will search for any type names in the schema in these go packages
# if they match it will use them, otherwise it will generate them.
# autobind:
#   - "github.com/99designs/gqlgen/_examples/federation/reviews/graph/model"

# This section declares type mapping between the GraphQL and go type systems
#
# The first line in each type will be used as defaults for resolver arguments and
# modelgen, the others will be allowed when binding to fields. Configure them to
# your liking
models:
  User:
    fields:
      reviews:
        resolver: true
  Product:
    fields:
      reviews: 
        resolver: true
  ID:
    model:
      - github.com/99designs/gqlgen/graphql.ID
      - github.com/99designs/gqlgen/graphql.Int
      - github.com/99designs/gqlgen/graphql.Int64
      - github.com/99designs/gqlgen/graphql.Int32
  Int:
    model:
      - github.com/99designs/gqlgen/graphql.Int
      - github.com/99designs/gqlgen/graphql.Int64
      - github.com/99designs/gqlgen/graphql.Int32
```

As noted above, the samples use a different method to accomplish this: 

https://github.com/99designs/gqlgen/blob/master/_examples/federation/reviews/graph/model/models.go

https://github.com/99designs/gqlgen/blob/master/_examples/federation/reviews/gqlgen.yml#L36-L37 does that by not implementing the specific fields in the model.
