### ISSUE TITLE
Embed generation with plugins fails

### ISSUE THREAD

**Issue by bakjos** [99designs/gqlgen#2204]
### What happened?
When the config file includes generates the sources in the same directory where the schema is, and includes a plugin generating additional sources, like federation, it triggers an error during the validation phase: 

`validation failed: packages.Load: graphql_gen.go:298:29: pattern federation/directives.graphql: no matching files found`

And the generated code contains the following in the line 298
```go
//go:embed "schema.graphql" "federation/directives.graphql" "federation/entity.graphql"
var sourcesFS embed.FS
```

Here's the config:

```yaml
schema:
  - "*.graphql"

# Where should the generated server code go?
exec:
  filename: graphql_gen.go
  package: graphql

# Uncomment to enable federation
federation:
  filename: federation_gen.go
  package: graphql
  version: 2

# Where should any generated models go?
model:
  filename: models_gen.go
  package: graphql

# Where should the resolver implementations go?
resolver:
  layout: follow-schema
  dir: .
  package: graphql
models:
  ID:
    model:
      - github.com/99designs/gqlgen/graphql.ID
      - github.com/99designs/gqlgen/graphql.Int
      - github.com/99designs/gqlgen/graphql.Int64
      - github.com/99designs/gqlgen/graphql.Int32
  Int:
    model:
      - github.com/99designs/gqlgen/graphql.Int
      - github.com/99designs/gqlgen/graphql.Int64
      - github.com/99designs/gqlgen/graphql.Int32
  Time:
    model:
      - github.com/99designs/gqlgen/graphql.Time
...
```

### What did you expect?
To run as in the version v0.17.5,  I think this error was introduced by the embedded PR https://github.com/99designs/gqlgen/pull/2119
### Minimal graphql.schema and models to reproduce
Happens with any schema using federation
### versions
 - `go run github.com/99designs/gqlgen version`? v0.17.8
 - `go version`? go version go1.18.2 darwin/amd64
