### ISSUE TITLE
missing package name for models in resolveManyEntities routine 

### ISSUE THREAD

**Issue by jdavisclark** [99designs/gqlgen#2472]
### What happened?
If you utilize a config where autogenerated models and federation code are in different packages and `@entityResolver(multi:true)` is present on some of your federated types, the generated code re the `_rep` input slice in the `resolveManyEntities` routine is missing the package name for the input types.

### What did you expect?
valid code

### Minimal graphql.schema and models to reproduce
gqlgen.yml:
```yaml
schema:
  - internal/graphql/schema/**/*.graphql

exec:
  filename: internal/graphql/generated/generated.go
  package: generated

federation:
  filename: internal/graphql/generated/federation.go
  package: generated
  version: 2

model:
  filename: internal/graphql/gqlmodels/gqlmodels.go
  package: gqlmodels

resolver:
  layout: follow-schema
  dir: internal/graphql/resolvers
  package: resolvers
  filename_template: "{name}.resolvers.go"

omit_slice_element_pointers: true

models:
  ID:
    model:
      - github.com/99designs/gqlgen/graphql.String
      - github.com/99designs/gqlgen/graphql.Int
      - github.com/99designs/gqlgen/graphql.ID
```

schema:
```graphql
directive @entityResolver(multi: Boolean) on OBJECT

type Customer @key(fields: "id") @entityResolver(multi: true) {
    id: ID!
    name: String
}
```

diff required to fix autogenerated code:
```diff
From e623279096b8eeef99dfa757a202a0c6c001c164 Mon Sep 17 00:00:00 2001
From: jdavisclark
Date: Tue, 13 Dec 2022 16:49:51 -0600
Subject: [PATCH] manually fix gqlgen

---
 internal/graphql/generated/federation.go | 5 +++--
 1 file changed, 3 insertions(+), 2 deletions(-)

diff --git a/internal/graphql/generated/federation.go b/internal/graphql/generated/federation.go
index d6b1399..5e70360 100644
--- a/internal/graphql/generated/federation.go
+++ b/internal/graphql/generated/federation.go
@@ -6,6 +6,7 @@ import (
 	"context"
 	"errors"
 	"fmt"
+	"github.com/yourOrg/yourRepo/internal/graphql/gqlmodels"
 	"strings"
 	"sync"
 
@@ -99,7 +100,7 @@ func (ec *executionContext) __resolve_entities(ctx context.Context, representati
 		switch typeName {
 
 		case "Customer":
-			_reps := make([]*CustomerByIDsInput, len(reps))
+			_reps := make([]gqlmodels.CustomerByIDsInput, len(reps))
 
 			for i, rep := range reps {
 				id0, err := ec.unmarshalNID2string(ctx, rep["id"])
@@ -107,7 +108,7 @@ func (ec *executionContext) __resolve_entities(ctx context.Context, representati
 					return errors.New(fmt.Sprintf("Field %s undefined in schema.", "id"))
 				}
 
-				_reps[i] = &CustomerByIDsInput{
+				_reps[i] = gqlmodels.CustomerByIDsInput{
 					ID: id0,
 				}
 			}
-- 
2.24.0
```

### versions
 - `go run github.com/99designs/gqlgen version`?
   -   v0.17.20
 - `go version`?
   - go version go1.16.15 darwin/amd64
