### ISSUE TITLE
UInt fields now always require to write a getter resolver

### ISSUE THREAD

**Issue by mdestagnol** [99designs/gqlgen#2550]
The behavior is a regression between 0.17.22 and 0.17.24. 

On 0.17.24, everytime an object contain an UInt field, that field requires to write a resolver getter or it triggers the following error:

`ID is incompatible with uint`

On 0.17.22 GQLgen was able to figure it out.

**Comment by mstephano** [comment]
Hi @mdestagnol, can you provide code example of your issue?

**Comment by mstephano** [comment]
Can you also verify if your scenario is not covered in the [scalars ](https://github.com/99designs/gqlgen/tree/master/_examples/scalars)example?

**Comment by mdestagnol** [comment]
I confirm I don't think it is

**Comment by mstephano** [comment]
@mdestagnol Any follow up on your side?

**Comment by ryan-lang** [comment]
I believe I'm encountering the same issue, after upgrading from 0.17.1 to 0.17.24. The following was working correctly in 0.17.1.

```yaml
# gqlgen.yaml

models:
  Uint:
    model:
      - github.com/99designs/gqlgen/graphql.Uint32
      - github.com/99designs/gqlgen/graphql.Uint
      - github.com/99designs/gqlgen/graphql.Uint64
```

```graphql
# schema.graphqls

scalar Uint

type PagedList {
  totalCount: Uint!
  pageNumber: Uint!
  pageSize: Uint!
  items: [Item!]!
}

type Query{
  tableItems: PagedList!
}

```

In the new version, a `pagedListResolver` type is being generated, with required getter resolvers for `TotalCount`, `PageNumber`, and `PageSize`.

```golang
func (r *pagedListResolver) TotalCount(ctx context.Context, obj *model.PagedList) (uint32, error) {
	panic(fmt.Errorf("not implemented: TotalCount - totalCount"))
}
// etc...
```

**Comment by ryan-lang** [comment]
Further investigation shows the version the introduces the new behavior is 0.17.23.

**Comment by mstephano** [comment]
@ryan-lang The change was to not need a scalar for `uint` and `uint32`, and be able to use `Int` directly in graphql for those type. However, the uint64 will still need a scalar with custom marshalling because it is bigger than int64.

For your code, are you able to detect what fields are uint and uint32, and put them as Int in your graphqls file? Also remove them from gqlgen.yaml under model of scalar Uint. Let me know if it works:

ex:
```yaml
# gqlgen.yaml

models:
  Uint:
    model:
      - github.com/99designs/gqlgen/graphql.Uint64
```

```graphql
# schema.graphqls

scalar Uint

type PagedList {
  totalCount: Uint!
  pageNumber: Int!
  pageSize: Int!
  items: [Item!]!
}

type Query{
  tableItems: PagedList!
}
```
