### ISSUE TITLE
Automatically create resolvers for all fields

### ISSUE THREAD

**Issue by martinscholz83** [99designs/gqlgen#2702]
### What happened?
Currently to create a resolver for field you have to explicitly set this in the config file like this
```
Todo:
    fields:
      user:
        resolver: true
```
### What did you expect?
Is there any way to by default create resolvers for all fields in the schema. Wether they are used or not.
### versions
 - `v0.17.34`
 - `1.20`
