### ISSUE TITLE
Question: Resolver Execution Order

### ISSUE THREAD

**Issue by leechuyemdev** [99designs/gqlgen#2737]
Hey team, is there a way to execute the parent resolver in parallel with the children resolver?

### What happened?
**Resolver**
```
ParentA:
    fields:
      ChildA:
        resolver: true
      ChildB:
        resolver: true
```

Currently the execution order is:
- ParentA
   - ChildA
   - ChildB

I would like the execution order to be:
- ParentA
- ChildA
- ChildB

Is this possible?
### versions
 - `go run github.com/99designs/gqlgen version`?
 - `go version`?
