### ISSUE TITLE
Generate a separate resolver file per schema

### ISSUE THREAD

**Issue by paxer** [99designs/gqlgen#2754]
### What happened?
I am using the default config and when I add a new schema, for instance,`anothershema.graphqls` to the same folder where the default `schema.graphqls`  and run `go generate` - it does not generate a new `anothershema.resolver.go`but instead it adds a new methods based on the new schema to the existing `schema.resolvers.go`
### What did you expect?
according to the config
```
resolver:
  layout: follow-schema
  dir: graph/resolvers
  package: graph
  filename_template: "{name}.resolvers.go"
```
If I add a new schema `anothershema.graphqls` and then I `go generate` I expect to see a new resolver `anothershema.resolver.go` file is generated

### versions
 - `go run github.com/99designs/gqlgen version`? - v0.17.36
 - `go version`? - 1.20.6
