### ISSUE TITLE
Autobind using relative path?

### ISSUE THREAD

**Issue by JamesArthurHolland** [99designs/gqlgen#2760]
Is it possible to use autobind with relative path?

This works:
```yaml
models:
  Profile:
    model:
      - ../profile/api/profile/v1.Profile
```

This doesn't:
```yaml
autobind:
  - ../profile/api/profile/v1
```

I've also tried a lot of other combinations of the relative path. No luck
