### ISSUE TITLE
Forcing resolver on scalar of field in existing struct results in ignoring nullability of schema type

### ISSUE THREAD

**Issue by BitPhinix** [99designs/gqlgen#277]
### Expected Behaviour

creation and birthday resolvers should be of type
`func(ctx context.Context, obj *some.Account) (*time.Time, error)`

### Actual Behavior

creation resolver is of different type (non-pointer)
`func(ctx context.Context, obj *some.Account) (time.Time, error)`

### Minimal graphql.schema and models to reproduce

Model:
```
type Account struct {
    Info              Info
    Creation     time.Time
}

type Info struct {
    Birthday   time.Time
}
```

Schema:
```
scalar Date

type Account {
    creation: Date
    birthday: Date
}
```

Date resolver:
```
func MarshalDate(t time.Time) graphql.Marshaler {
    return graphql.WriterFunc(func(w io.Writer) {
        io.WriteString(w, strconv.FormatInt(t.Unix(), 10))
    })
}

func UnmarshalDate(v interface{}) (time.Time, error) {
    if i, ok := v.(int); ok {
        return time.Unix(int64(i), 0), nil
    }

    return time.Time{}, errors.New("date should be a unix timestamp")
}
```

gqlgen.yml:
```
...
models:
  Account:
    model: "some/path.Account"
    fields:
      creation:
        resolver: true
  Date:
    model: "some/path.Date"
...
```
