### ISSUE TITLE
Can't make UUID work with Gqlgen

### ISSUE THREAD

**Issue by Loschcode** [99designs/gqlgen#2790]
### What happened?
I followed this documentation https://gqlgen.com/reference/scalars/ and it didn't work.

### What did you expect?
To be able to generate the schema without problem

### Minimal graphql.schema and models to reproduce
```
// schema.graphql
scalar Time
scalar UUID

type Organization {
    id: UUID!
    email: String!
    password: String!
    accessToken: String!
    createdAt: Time!
    updatedAt: Time!
}

extend type Mutation {
    Signup(email: String!, password: String!): Organization
    Signin(email: String!, password: String!): Organization
}

extend type Query {
    GetOrganization(id: UUID!): Organization
}
```

Also inside of `gqlgen.yml` I have

```

models:
  UUID:
    model:
      - github.com/99designs/gqlgen/graphql.UUID # I added this one manually
  ID:
    model:
      - github.com/99designs/gqlgen/graphql.ID
      - github.com/99designs/gqlgen/graphql.Int
      - github.com/99designs/gqlgen/graphql.Int64
      - github.com/99designs/gqlgen/graphql.Int32
  Int:
    model:
      - github.com/99designs/gqlgen/graphql.Int
      - github.com/99designs/gqlgen/graphql.Int64
      - github.com/99designs/gqlgen/graphql.Int32
```

### versions
0.17.36

```
> make generate
go get github.com/99designs/gqlgen@v0.17.36 && go run github.com/99designs/gqlgen && go run ./app/models/model_tags/model_tags.go
modelgen: unable to find type: github.com/99designs/gqlgen/graphql.UUID
exit status 1
make: *** [generate] Error 1
```
