### ISSUE TITLE
Unable to find graphql.Duration

### ISSUE THREAD

**Issue by Loschcode** [99designs/gqlgen#2828]
### What happened?

```
❯ go run github.com/99designs/gqlgen
modelgen: unable to find type: github.com/99designs/gqlgen/graphql.Duration
exit status 1
```

### What did you expect?

I expected the generation to be successful. I just added `graphql.Duration` as explained in your documentation.

### Minimal graphql.schema and models to reproduce

```
  UUID:
    model:
      - github.com/99designs/gqlgen/graphql.UUID
  ID:
    model:
      - github.com/99designs/gqlgen/graphql.ID
      - github.com/99designs/gqlgen/graphql.Int
      - github.com/99designs/gqlgen/graphql.Int64
      - github.com/99designs/gqlgen/graphql.Int32
  Int:
    model:
      - github.com/99designs/gqlgen/graphql.Int
      - github.com/99designs/gqlgen/graphql.Int64
      - github.com/99designs/gqlgen/graphql.Int32
  Duration:
    model:
      - github.com/99designs/gqlgen/graphql.Duration
```

### versions
- GQLGen: v0.17.37
- Go: go version go1.20.6 darwin/amd64
