### ISSUE TITLE
gqlgen v0.17.42 breaks / incompatible with gqlgenc vv0.16.0

### ISSUE THREAD

**Issue by matoszz** [99designs/gqlgen#2874]
### What happened?

When pulling the update for gqlgen v0.17.42, there was an introduction of the creation of empty `Query` and `Mutation` structs which now conflict with the gqlgenc generated client that contain the same structs; an example diff I'm seeing when pulling in the new version can be seen [here](https://github.com/datumforge/datum/commit/c9f1609baec46428395990edc52378c7e69aa161#diff-b5d9ab1e460459606768db9b68889b322e7396628ecce0ee8c7bed3f531aea70R1073)

### What did you expect?

The underlying client generated models shouldn't contain empty Mutation and Query structs

### Minimal graphql.schema and models to reproduce

I believe you can reproduce this with any schema, but specifically with the gqlgenc client generation enabled in conjunction with gqlgen. I've forked my underlying repo and generated the diff created by gqlgen / gqlgenc [here](https://github.com/datumforge/datum/commit/c9f1609baec46428395990edc52378c7e69aa161#diff-b5d9ab1e460459606768db9b68889b322e7396628ecce0ee8c7bed3f531aea70R1073)

### versions
 - `go run github.com/99designs/gqlgen version v0.17.42`?
 - `go version 1.21.5`?

**Comment by ghjm** [comment]
This issue is affecting me as well.

**Comment by udhaykumarB** [comment]
same issue here

**Comment by skid-rock** [comment]
Same problem. Need to do something

**Comment by ghjm** [comment]
If my PR https://github.com/99designs/gqlgen/pull/2878 is merged (and is included in a release, etc), you will be able to specify a new configuration option `omit_root_models: true` that will fix this.

**Comment by matoszz** [comment]
@ghjm I'm testing gqlgen @ `v0.17.43` (with #2878)  + `omit_root_models: true` and gqlgenc @  `v0.18.0` and  it doesn't seem as though this flag (regardless of it's settings) is getting picked up. I attempted both true/false and noticed that there was _no_ change output when running gqlgen directly (good) but when running gqlgenc it still outputs the base models regardless of the settings I have within `gqlgen.yml` - any advice? you see this working in-practice yet?

**Comment by ghjm** [comment]
The client generator has always generated these base models.  If you want gqlgenc not to output them, that would require a change in https://github.com/Yamashou/gqlgenc, not here.  This PR just (optionally) prevents gqlgen from generating them, so that it doesn't conflict with gqlgenc.

**Comment by ghjm** [comment]
Also, now that the PR has been merged, this issue can be closed.  Cc @StevenACoffman

**Comment by matoszz** [comment]
@ghjm shouldn't the change of the bool option in the `gqlgen.yml` actually produce a change in the output when generating? I guess I would have expected when uncommenting out that option in the configuration and running the generate commands that i'd see a diff in output with the option on / off but there's no file changes when doing so.

I originally reported this issue when the version of gqlgen I was trying to pull in started behaving in this way, but it seems as though it's always been erroneously generated by `gqlgenc` all along (I can bump gqlgenc version and not change gqlgen, generates fine; if i bump the gqlgen version + gqlgenc i get the empty structs)

**Comment by ghjm** [comment]
You must be generating different packages for the client and the server.  I was trying to avoid this, because I also use the generated structs for internal data handling, and I didn't want to have two different type systems for client-side and server-side representations of identical objects.  So for me it is a problem that gqlgen started generating the empty Query and Mutation structs, because they conflict with the same-named structs generated by gqlgenc.

Whatever you're trying to do, it's not the same as what I was trying to do.  This PR does solve my problem and I'm now able to upgrade to latest-version gqlgen without problems, as long as I set the configuration flag.

**Comment by ghjm** [comment]
And maybe this issue shouldn't be closed since it is apparently not solved for @matoszz, who opened the issue.

**Comment by matoszz** [comment]
@ghjm interesting, appreciate the response / feedback - I may be inadvertently generating different packages for the client and server as your description seems like what i'm trying to accomplish as I also use the generated structs for internal data handling. Would you mind sharing your gqlgen + gqlgenc configuration(s)? It'd be helpful for me to see how you're managing these as a single package in practice.

In my gqlgen.yml I have:
```
schema:
  - schema/*.graphql

exec:
  filename: internal/graphapi/gen_server.go
  package: graphapi

model:
  filename: internal/graphapi/gen_models.go
  package: graphapi

resolver:
  layout: follow-schema
  dir: internal/graphapi
  package: graphapi
  filename_template: "{name}.resolvers.go"

omit_gqlgen_version_in_file_notice: true

autobind:
 - "github.com/datumforge/datum/internal/graphapi"
 - "github.com/datumforge/datum/internal/ent/generated"
```

and gqlgenc.yml:

```
schema: ["schema.graphql" ]
query: ["query/*.graphql"]
model:
  package: datumclient
  filename: ./internal/datumclient/models.go
client:
  package: datumclient
  filename: ./internal/datumclient/graphclient.go
generate:
  clientV2: true
  clientInterfaceName: "DatumClient"
```
is it as simple as making the package names the same and aligning the model file names?

**Comment by Yamashou** [comment]
A new version has been released to allow Query and Mutation to not be generated
```
generate:
  clientV2: true
  clientInterfaceName: "GithubGraphQLClient"
  query: false
  mutation: false
```
https://github.com/Yamashou/gqlgenc/releases/tag/v0.18.0
