### ISSUE TITLE
Can't upgrade from 0.3.0 to 0.4.3

### ISSUE THREAD

**Issue by rhymes** [99designs/gqlgen#288]
I've been trying to upgrade from 0.3.0 to 0.4.3 without success.

I've followed the steps that I've found in the release notes of https://github.com/99designs/gqlgen/releases/tag/0.4.0:

* replaced `vektah/gqlgen` with `99designs/gqlgen`
* removed the `generated.go` file
* ran `dep ensure -update github.com/99designs/gqlgen github.com/vektah/gqlparser`
* ran `go generate ./...`

Instead I get an error saying it can find  the package `introspection`. I checked inside vendor and indeed this folder is not present: `https://github.com/99designs/gqlgen/tree/master/graphql/introspection`

So I tried to remove the vendor folder altogether and re-run `dep ensure` but nothing changed:

```
➜ ls vendor/github.com/99designs/gqlgen/graphql/introspection                                                                                                                                     ls: vendor/github.com/99designs/gqlgen/graphql/introspection: No such file or directory
➜ rm -fr vendor                                                                                                                                                                                   ➜ dep ensure                                                                                                                                                                                      ➜ ls vendor/github.com/99designs/gqlgen/graphql/introspection                                                                                                                                     ls: vendor/github.com/99designs/gqlgen/graphql/introspection: No such file or directory
```

### Expected Behaviour

I expect gqlgen to re-generate the file

### Actual Behavior

```text
go generate ./...
panic: cannot find package "github.com/99designs/gqlgen/graphql/introspection" in any of:
	~/project/vendor/github.com/99designs/gqlgen/graphql/introspection (vendor tree)
	/usr/local/Cellar/go/1.10.3/libexec/src/github.com/99designs/gqlgen/graphql/introspection (from $GOROOT)
	/Users/rhymes/Development/go/src/github.com/99designs/gqlgen/graphql/introspection (from $GOPATH)

goroutine 1 [running]:
project/vendor/github.com/99designs/gqlgen/codegen.(*Imports).add(0xc429ec58f0, 0x13a3c63, 0x31, 0xc42b556fc0)
	~/project/vendor/github.com/99designs/gqlgen/codegen/import_build.go:61 +0x2a3
project/vendor/github.com/99designs/gqlgen/codegen.buildImports(0xc4201e0ff0, 0xc4200fe2a0, 0x5b, 0x0)
	~/project/vendor/github.com/99designs/gqlgen/codegen/import_build.go:35 +0xe6
project/vendor/github.com/99designs/gqlgen/codegen.(*Config).models(0xc420511aa8, 0x69, 0x13d8a60, 0x1591300)
	~/project/vendor/github.com/99designs/gqlgen/codegen/build.go:58 +0x116
project/vendor/github.com/99designs/gqlgen/codegen.Generate(0xc4200a6810, 0xe, 0xc4201b8000, 0x558, 0xc4200fec40, 0x68, 0xc4200a6c38, 0x7, 0x0, 0x0, ...)
	~/project/vendor/github.com/99designs/gqlgen/codegen/codegen.go:25 +0xa3
project/vendor/github.com/99designs/gqlgen/cmd.glob..func1(0x15a8e00, 0x15c95e0, 0x0, 0x0)
	~/project/vendor/github.com/99designs/gqlgen/cmd/gen.go:86 +0x23a
project/vendor/github.com/spf13/cobra.(*Command).execute(0x15a8e00, 0xc42009a190, 0x0, 0x0, 0x15a8e00, 0xc42009a190)
	~/project/vendor/github.com/spf13/cobra/command.go:766 +0x2c1
project/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x15a8e00, 0x12b8fb9, 0xc4200ee200, 0x15abcf0)
	~/project/vendor/github.com/spf13/cobra/command.go:852 +0x30a
project/vendor/github.com/spf13/cobra.(*Command).Execute(0x15a8e00, 0xc420090058, 0x0)
	~/project/vendor/github.com/spf13/cobra/command.go:800 +0x2b
project/vendor/github.com/99designs/gqlgen/cmd.Execute()
	~/project/vendor/github.com/99designs/gqlgen/cmd/root.go:52 +0x2d
main.main()
	~/project/vendor/github.com/99designs/gqlgen/main.go:6 +0x20
nm/api/backend/backend.go:1: running "gorunpkg": exit status 2
make: *** [generate] Error 1
```

### Minimal graphql.schema and models to reproduce

My Gopkg.toml contains:

```toml
required = ["github.com/99designs/gqlgen"]

[[constraint]]
  name = "github.com/99designs/gqlgen"
  version = "0.4.3"
```

The generator line is: `//go:generate gorunpkg github.com/99designs/gqlgen`

Am I missing something? Do I need to add `github.com/99designs/gqlgen/graphql/introspection` as a separate package?

**Comment by lwc** [comment]
Can you try clobbering at least the gqlgen parts of your dep cache, located in `$GOPATH/pkg/dep/`?

**Comment by rhymes** [comment]
Removed the two folders I found (the vektha/gqlgen and the 99designs/gqlgen), the removed my vendor folder, then re-issued `dep ensure` and `go generate` but I get the same error. The cache contains the introspection folder:

```shell
~ ls $GOPATH/pkg/dep/sources/https---github.com-99designs-gqlgen/graphql/introspection                                                                                                                                           introspection.go query.go         schema.go        type.go          type_test.go
```
my vendored copy doesn't:

```shell
~ ls vendor/github.com/99designs/gqlgen/graphql/introspection                                                                                                                                     ls: vendor/github.com/99designs/gqlgen/graphql/introspection: No such file or directory
```

This is strange :D

**Comment by vektah** [comment]
Did you get this fixed? Its worth checking what git hash is in `Gopkg.lock` and making sure dep found the 0.4.3 release.
If the hash looks good, try deleting `vendor` and running `dep ensure -vendor-only` to grab a fresh vendor
if it the hash looks old, does `dep ensure -update github.com/99designs/gqlgen` tell you why it didnt update anything?

**Comment by rhymes** [comment]
This what I had until now in the Gopkg.lock file:

```toml
[[projects]]
  digest = "1:aa5103494cd91acb7660659e55da80a00d4372e577279581a1f17f8c855e378b"
  name = "github.com/99designs/gqlgen"
  packages = [
    ".",
    "cmd",
    "codegen",
    "codegen/templates",
    "graphql",
    "handler",
  ]
  pruneopts = "UT"
  revision = "3575c289486fce174c941b63749b9bbb88c3ca90"
  version = "0.4.3"
```

This is what I have in the Gopkg.toml:

```toml
required = ["github.com/99designs/gqlgen"]

[[constraint]]
  name = "github.com/99designs/gqlgen"
  version = "0.4.3"
```

I then deleted the vendor folder, ran `dep ensure -vendor-only`, opened the vendor folder by `graphql/introspection` still isn't there :-(

![screen shot 2018-08-20 at 3 05 44 pm](https://user-images.githubusercontent.com/146201/44342247-aece5500-a48a-11e8-92d9-77d4712dbf71.png)

I also get the same error from `go generate`.

I asked myself if maybe there's an issue with how 0.4.3 is packaged or with dep itself...

I then tried to point dep to gqlgen master:

```toml
[[projects]]
  branch = "master"
  digest = "1:ced9793c6ea0d4c1219dec075d9a76c36f051f3d2797c5cada023a4cb66a1570"
  name = "github.com/99designs/gqlgen"
  packages = [
    ".",
    "cmd",
    "codegen",
    "codegen/templates",
    "graphql",
    "handler",
  ]
  pruneopts = "UT"
  revision = "719172670d1c5f80e819bf1376edb8e1f9ed59f3"
```

 Right now I noticed something: 

* Gopkg.lock lists cmd, codegen, codegen/templates, graphql and handler as gqlgen packages
* `graphql/introspection.go` sits in a `introspection` package inside `graphql` package

I then tried to hack it by modifying Gopkg.lock directly:

```toml

[[projects]]
  branch = "master"
  digest = "1:ced9793c6ea0d4c1219dec075d9a76c36f051f3d2797c5cada023a4cb66a1570"
  name = "github.com/99designs/gqlgen"
  packages = [
    ".",
    "cmd",
    "codegen",
    "codegen/templates",
    "graphql",
    "graphql/introspection",
    "handler",
  ]
  pruneopts = "UT"
  revision = "719172670d1c5f80e819bf1376edb8e1f9ed59f3"
```

(I added `graphql/introspection` in the list of packages)

Then removed the vendor folder and issued `dep ensure -vendor-only` and now I can see the folder and its files in all their glory :-)

![screen shot 2018-08-20 at 3 14 22 pm](https://user-images.githubusercontent.com/146201/44342575-c35f1d00-a48b-11e8-9fa7-946552cac0fd.png)

I'm not sure what the solution is but at least now we know what the problem is :-)
