### ISSUE TITLE
Federation error `federation and exec must be in the same package`

### ISSUE THREAD

**Issue by phoenixTW** [99designs/gqlgen#3119]
### What happened?
Trying to configure federation but found this error

```sh
failed to load schema: federation and exec must be in the same package
exit status 1
make: *** [generate] Error 1
```

#### gqlgen.yml
```yml
schema:
  - schemas/*.graphqls

exec:
  dir: internal/infra/graph/generated
  package: generated

federation:
  filename: internal/infra/graph/generated/federation.go
  package: generated
  version: 2

model:
  filename: internal/infra/graph/model/models_gen.go
  package: model

resolver:
  layout: follow-schema
  dir: internal/infra/resolvers
  package: resolvers
  filename_template: "{name}_resolver.go"

models:
  ID:
    model:
      - github.com/99designs/gqlgen/graphql.ID
      - github.com/99designs/gqlgen/graphql.Int
      - github.com/99designs/gqlgen/graphql.Int64
      - github.com/99designs/gqlgen/graphql.Int32
  Int:
    model:
      - github.com/99designs/gqlgen/graphql.Int
      - github.com/99designs/gqlgen/graphql.Int64
      - github.com/99designs/gqlgen/graphql.Int32
  UUID:
    model:
      - github.com/99designs/gqlgen/graphql.UUID

```

### What did you expect?
The generate should work as expected and it generates the federated content in `federation.go`

### Minimal graphql.schema and models to reproduce
```graphql
type Product @key(fields: "id") {
    id: ID!
    name: String!
}

type Query {
  products: [Product!]!
}

```

### versions
 - `go run github.com/99designs/gqlgen version`?  - `v0.17.47`
 - `go version`? - `1.20`
