### ISSUE TITLE
Gqlgen not compliant with graphql spec for Int type

### ISSUE THREAD

**Issue by roeest** [99designs/gqlgen#3214]
### What happened?
Gqlgen treats the `Int` graphql type as a golang 64 bit integer. The [graphql spec](https://spec.graphql.org/October2021/#sec-Int) states that the `Int` graphql type represents a 32 bit integer. This causes issues with clients that assume the underlying type of an integer is 32 bits either by overflowing them or by making them error out altogether.

### What did you expect?

Behavior that matches the graphql spec
1. Error when specifying an `Int` input that overflows 32bit integers
2. Truncate `Int` results that overflow or even better return an indicative error

### Minimal graphql.schema and models to reproduce
Any schema with an `Int` in an input or a regular type
### versions
 - `go run github.com/99designs/gqlgen version`? v0.17.49
 - `go version`? go version go1.22.4 darwin/arm64

**Comment by phughes-scwx** [comment]
@roeest does updating the `gqlgen.yaml` models section so that:

```yaml
models:
  ID:
    model:
      - github.com/99designs/gqlgen/graphql.ID
      - github.com/99designs/gqlgen/graphql.Int32
  Int:
    model:
      - github.com/99designs/gqlgen/graphql.Int32
```

Make the server spec-compliant, as you see it?
