### ISSUE TITLE
How do I add inputs to generated resolver for nested objects? 

### ISSUE THREAD

**Issue by pecks-bad-boy** [99designs/gqlgen#3232]
### What happened?
For resolvers generated like so:
```
Todo:
    fields:
      user:
        resolver: true
```
How do I add inputs so I can filter based on fields of the sub objects like what is shown in this article https://dgraph.io/docs/graphql/queries/search-filtering/?

### versions
 - v0.17.49
 - 1.22.5 darwin/arm64
