### ISSUE TITLE
@requires fields unable to deal with Union

### ISSUE THREAD

**Issue by rickbijkerk** [99designs/gqlgen#3342]
### What happened?
Code generation breaks when you apply an @requires to an Union field

if you run codegen for the following schema 
```
type Person @key(fields: "name"){
    name: String!
    gender: Gender!
    welcomeMessage: String @requires(fields:"gender { ... on Male {description} ... on Female {description}}")
}

union Gender = Male | Female

type Male {
    description: String!
}

type Female {
    description: String!
}
```

you'll get an exception:
```panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x30 pc=0x102a8df30]

goroutine 1 [running]:
github.com/99designs/gqlgen/plugin/federation/fieldset.fieldByName(0x102ce0a38?, {0x14000260681, 0x3})
        /Users/rickbijkerk/projects/gqlgen/plugin/federation/fieldset/fieldset.go:207 +0x20
github.com/99designs/gqlgen/plugin/federation/fieldset.Field.TypeReference({0x1400007f700?, 0x14000035990?, 0x14000029a70?}, 0x2a?, {0x140004f5100, 0x13, 0x6?})
        /Users/rickbijkerk/projects/gqlgen/plugin/federation/fieldset/fieldset.go:85 +0x100
github.com/99designs/gqlgen/plugin/federation.(*Federation).GenerateCode(0x1400025e150, 0x140000b8790)
        /Users/rickbijkerk/projects/gqlgen/plugin/federation/federation.go:297 +0xd48
github.com/99designs/gqlgen/api.Generate(0x140000e1688, {0x0, 0x0, 0x103029d20?})
        /Users/rickbijkerk/projects/gqlgen/api/generate.go:132 +0xb88
main.init.func2(0x1400008ab80?)
        /Users/rickbijkerk/projects/gqlgen/main.go:190 +0xa8
github.com/urfave/cli/v2.(*Command).Run(0x140000fc6e0, 0x1400008ab80, {0x14000020090, 0x1, 0x1})
        /Users/rickbijkerk/go/pkg/mod/pkg/mod/github.com/urfave/cli/v2@v2.27.5/command.go:276 +0x71c
github.com/urfave/cli/v2.(*App).RunContext(0x140000dc400, {0x102ce4530, 0x1030aa180}, {0x14000020090, 0x1, 0x1})
        /Users/rickbijkerk/go/pkg/mod/pkg/mod/github.com/urfave/cli/v2@v2.27.5/app.go:333 +0x51c
github.com/urfave/cli/v2.(*App).Run(...)
        /Users/rickbijkerk/go/pkg/mod/pkg/mod/github.com/urfave/cli/v2@v2.27.5/app.go:307
main.main()
        /Users/rickbijkerk/projects/gqlgen/main.go:227 +0x200
```

### What did you expect?
it to generate code and not throw any exceptions

### versions
 - v0.17.55
 - 1.23.0

gqlgen.yml

```
schema:
  - graph/*.graphql

exec:
  filename: graph/generated/generated.go
  package: generated

federation:
   filename: graph/generated/federation.go
   package: generated
   options:
     explicit_requires: true

model:
  filename: graph/model/models_gen.go
  package: model

resolver:
  layout: follow-schema
  dir: graph
  package: graph
```
