### ISSUE TITLE
Initialisms make some words codegen with weird capitalization

### ISSUE THREAD

**Issue by amruth-opal** [99designs/gqlgen#3441]
### What happened?
if you declare an enum in your schema like
```
enum MessagingPlatform {
  SLACK
}
```
the go type it codegens 

```
type MessagingPlatform string

const (
	MessagingPlatformSLACk                     MessagingPlatform = "SLACK"
)
```

I believe this is because Slack contains the initialism SLA so it's keeping the initialism capitalized and then capitalizing the first letter. Possible [relevant code file](https://github.com/99designs/gqlgen/blob/fbe0246f8c04793501996a76591ee3a43c5a9b43/codegen/templates/templates.go#L770)

### What did you expect?
I would expect a way to express that the SLA substring is not an initialism and have it look like `Slack`. What would you recommend to enable this?

### Minimal graphql.schema and models to reproduce
See above

### versions
 - `gqlgen version` v0.17.57
 - `go version` go version go1.23.4 darwin/arm64

**Comment by Brookke** [comment]
Hey @amruth-opal you could use the config option `go_initialisms` to drop all the default initialisms and replace them with your own which may help?

```
go_initialisms:
  replace_defaults: true # if true, the default initialisms will get dropped in favor of the new ones instead of being added
  initialisms: # List of initialisms to for Go names
    - 'CC' 
    - 'BCC'
```
