### ISSUE TITLE
Resolver method to nested model not created

### ISSUE THREAD

**Issue by marczahn** [99designs/gqlgen#350]
### Expected Behaviour
For a relation Card -> Question I expect in the card resolver a method like
~~~
func (r *cardResolver) Question(ctx context.Context, obj *models.Card) (models.Question, error) {
	panic("not implemented")
}
~~~
### Actual Behavior
There is no method for this

### Minimal graphql.schema and models to reproduce
same configuration as [here](https://github.com/99designs/gqlgen/issues/349)

**Comment by vektah** [comment]
If you want a resolver method when generating models use `resolver: true`.

eg:
```
models:
  Todo:
    fields:
      id:
        resolver: true # force a resolver to be generated
```
see https://gqlgen.com/config/
