### ISSUE TITLE
prelude.resolvers.go uses nonexistent package for __InputValueResolver, __TypeResolver

### ISSUE THREAD

**Issue by john-markham** [99designs/gqlgen#3575]
This issue is quite similar to https://github.com/99designs/gqlgen/issues/3517 but not exactly the same. In my case, an import is just fully missing from my prelude.resolvers.go file as opposed to the types being undefined. In my case, the types _are_ defined elsewhere in my project in a `generated` package, but gqlgen generates this prelude.resolvers.go file

```go
package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"fmt"

	"github.com/99designs/gqlgen/graphql/introspection"
)

// IsDeprecated is the resolver for the isDeprecated field.
func (r *__InputValueResolver) IsDeprecated(ctx context.Context, obj *introspection.InputValue) (bool, error) {
	panic(fmt.Errorf("not implemented: IsDeprecated - isDeprecated"))
}

// DeprecationReason is the resolver for the deprecationReason field.
func (r *__InputValueResolver) DeprecationReason(ctx context.Context, obj *introspection.InputValue) (*string, error) {
	panic(fmt.Errorf("not implemented: DeprecationReason - deprecationReason"))
}

// IsOneOf is the resolver for the isOneOf field.
func (r *__TypeResolver) IsOneOf(ctx context.Context, obj *introspection.Type) (*bool, error) {
	panic(fmt.Errorf("not implemented: IsOneOf - isOneOf"))
}

// __InputValue returns generated.__InputValueResolver implementation.
func (r *Resolver) __InputValue() generated.__InputValueResolver { return &__InputValueResolver{r} }

// __Type returns generated.__TypeResolver implementation.
func (r *Resolver) __Type() generated.__TypeResolver { return &__TypeResolver{r} }

type (
	__InputValueResolver struct{ *Resolver }
	__TypeResolver       struct{ *Resolver }
)
```

elsewhere in prelude.generated.go 

```go
type __InputValueResolver interface {
	IsDeprecated(ctx context.Context, obj *introspection.InputValue) (bool, error)
	DeprecationReason(ctx context.Context, obj *introspection.InputValue) (*string, error)
}
type __TypeResolver interface {
	IsOneOf(ctx context.Context, obj *introspection.Type) (*bool, error)
}
```

So the resulting error is

```
internal/graph/resolver/prelude.resolvers.go:30:35: undefined: generated
internal/graph/resolver/prelude.resolvers.go:33:29: undefined: generated
```

as opposed to the original issue's error of: 

```
schema/resolvers/prelude.resolvers.go:31:42: undefined: server.__InputValueResolver
schema/resolvers/prelude.resolvers.go:34:36: undefined: server.__TypeResolver
```

This happens when upgrading from github.com/vektah/gqlparser/v2 v2.5.16 to github.com/vektah/gqlparser/v2 v2.5.22.

I was able to get around this issue at first by downgrading gqlparser. Then the actual fix came when changing my `go:generate go run -mod=mod github.com/99designs/gqlgen` to `go:generate go run -mod=mod github.com/99designs/gqlgen@v0.17.49` (as suggested in the original issue). After deleting prelude.resolvers.go, it was not regenerated. 

At first I thought that my local environment just had a different version of gqlgen installed than `v.0.17.49` (someone else generated the original prelude.resolvers.go file with what looks to be the correct version) which could lead to inconsistencies in the GraphQL Spec version (mentioned in https://github.com/vektah/gqlparser/issues/346).

@StevenACoffman Could this be a different issue? Feel free to mark as duplicate if not, but I'm just curious to actually understand why this fixes things.

**Comment by john-markham** [comment]
My gqlgen.yml: 

```yaml
# Where are all the schema files located? globs are supported eg  src/**/*.graphqls
schema:
  - schema/**/*.graphql

# Where should the generated server code go?
exec:
  layout: follow-schema
  dir: generated
  package: generated

# Uncomment to enable federation
federation:
  filename: generated/federation.go
  package: generated
  version: 2

# Where should any generated models go?
model:
  filename: model/models_gen.go
  package: model

omit_getters: true

# Where should the resolver implementations go?
resolver:
  layout: follow-schema
  dir: resolver
  package: resolver

# Skip running `go mod tidy` when generating server code
# This change is added to gqlgen 1.4
skip_mod_tidy: false


# We've started running into the upper limit of Go and were getting "NewBulk too big" errors. Disabling
# complexity as recommended by the PR that introduced it - https://github.com/99designs/gqlgen/pull/2504
omit_complexity: true

# Optional: turn on use `gqlgen:"fieldName"` tags in your models
# struct_tag: json

# Optional: turn on to use []Thing instead of []*Thing
omit_slice_element_pointers: true

# Optional: set to speed up generation time by not performing a final validation pass.
skip_validation: true

# gqlgen will search for any type names in the schema in these go packages
# if they match it will use them, otherwise it will generate them.
autobind:
  - 'github.cbhq.net/infra/graphql-monolith/internal/graph/model'

# This section declares type mapping between the GraphQL and go type systems
#
# The first line in each type will be used as defaults for resolver arguments and
# modelgen, the others will be allowed when binding to fields. Configure them to
# your liking
models:
  ID:
    model:
      - github.com/99designs/gqlgen/graphql.ID
      - github.com/99designs/gqlgen/graphql.Int
      - github.com/99designs/gqlgen/graphql.Int64
      - github.com/99designs/gqlgen/graphql.Int32
  Int:
    model:
      - github.com/99designs/gqlgen/graphql.Int
      - github.com/99designs/gqlgen/graphql.Int64
      - github.com/99designs/gqlgen/graphql.Int32
  TransferDeposit:
    fields:
      verification:
        resolver: true
```
