### ISSUE TITLE
How do I generate multiple models?

### ISSUE THREAD

**Issue by root9464** [99designs/gqlgen#3634]
I read in the documentation that it is possible to generate multiple generated files.go for each module (for example), but there is not a word about how you can generate models for each module in this way.

I have a task: there are 2 modules
/modules/test/model
/modules/test2/model 
after code generation, I want to have my own model in each of these directories based on the gql schema.

screen my filesctruct 

![Image](https://github.com/user-attachments/assets/f7394969-2a57-475a-a239-b92f3550833d)

my gqlgen.yml
```
schema:
  - modules/*/gql/schema.gql

exec:
  filename: packages/generated/generated.go
  package: generated

model:
  filename: packages/generated/models_gen.go
  package: generated

resolver:
  layout: follow-schema
  dir: modules
  package: gql

autobind:
  - github.com/root9464/Go_GamlerDefi/modules/test/model
  - github.com/root9464/Go_GamlerDefi/modules/test_user/model

models:
  ID:
    model:
      - github.com/99designs/gqlgen/graphql.ID
      - github.com/99designs/gqlgen/graphql.Int
      - github.com/99designs/gqlgen/graphql.Int64
      - github.com/99designs/gqlgen/graphql.Int32
  Int:
    model:
      - github.com/99designs/gqlgen/graphql.Int
      - github.com/99designs/gqlgen/graphql.Int64
      - github.com/99designs/gqlgen/graphql.Int32

```
