### ISSUE TITLE
Split generated stubs into multiple files

### ISSUE THREAD

**Issue by ariffebr** [99designs/gqlgen#377]
can we generate go-code based on schema to multiple files and if the file is already exist, then just update the files ?

may be like bellow :

>schema.graphql
```
schema {
    query: MyQuery
    mutation: MyMutation
}

type MyQuery {
    todo(id: Int!): Todo
    lastTodo: Todo
    todos: [Todo!]!
}

type MyMutation {
    createTodo(todo: TodoInput!): Todo!
    updateTodo(id: Int!, changes: Map!): Todo
}

type Todo {
    id: Int!
    text: String!
    done: Boolean!
}

input TodoInput {
    text: String!
    done: Boolean
}
```

>gqlgen.yml
```
schema: schema/schema.graphql
exec:
  filename: generated/generated.go
  package: generated
model:
  filename: models/model.go
#  multiple_files: true ## maybe we can add this config
resolver:
  filename: resolvers/resolver.go
  package: resolvers
#  multiple_files: true ## maybe we can add this config
  type: Resolver
struct_tag: json
```

>generated files
```
models/
     model.go
     todo.go
     todoInput.go
resolvers/
     resolver.go
     queryResolver.go
     mutationResolver.go
     todoResolver.go
```

it would be nice if we can work on specific file.

Thank you.

**Comment by mathewbyrne** [comment]
The base generated server will likely always go into a single output file, but I can see a use-case for splitting up resolver stubs.  Our stub generation still has a few issues, but I've marked this as an enhancement that we might consider when we look at improving it.

**Comment by ariffebr** [comment]
@mathewbyrne thank for your consideration.
happy monday. 😄

**Comment by vetcher** [comment]
I've got similar issue, my schema contain ~160 types and 100 queries/mutations, so my `generated.go` contain 35k lines. It will be great, if gqlgen will generate interfaces, complexity, queries, mutations and subs in separate files

**Comment by andrewmunro** [comment]
@vektah Regarding models, could we do something like this:

```
models:
  Todo:
    #model: path/to/existing/model.Todo <-- for linking to existing model
    filename: internal/graphql/model_gen.go <-- for generating a new model
    package: todo
```

Where instead of binding models to existing models, you could instead specify a filename and package for gqlgen to generate the stubs.

This would help when splitting up a project based on domain like so:
```
todo/
     service.go
     model_gen.go
     logger.go
todo/
     service.go
     model_gen.go
     logger.go
graphql/
     generated.go
     resolver/
          resolver.go
          query.go
          mutation.go
          todo.go <-- calls to todo package
          user.go <-- calls to user package
rest/
     handler/
          todo.go <-- calls to todo package
          user.go <-- calls to user package
```
This would massively help decouple a project from graphql if you wanted to say, add a cli interface or a restful interface...
