### ISSUE TITLE
go generate ./... results in cannot find package

### ISSUE THREAD

**Issue by emil-nasso** [99designs/gqlgen#384]
I have an app that I just upgraded from an older version of gqlgen. I followed the getting started guide and everything seems to be working, except for the code generation.

### Expected Behaviour

The code is generated when I run `go generate ./...`

### Actual Behavior

When running `go generate ./...` i get the 
pkg: cannot find package "github.com/99designs/gqlgen" in any of:
	/Users/emil/go/src/gitlab.com/the.nasso/daily-digest/vendor/github.com/99designs/gqlgen (vendor tree)
	/usr/local/Cellar/go/1.11.1/libexec/src/github.com/99designs/gqlgen (from $GOROOT)
	/Users/emil/go/src/github.com/99designs/gqlgen (from $GOPATH)
server/app.go:1: running "gorunpkg": exit status 1

### Minimal graphql.schema and models to reproduce

The contents of `vendor/github.com/99designs/gqlgen` are available here:
https://gitlab.com/the.nasso/daily-digest/tree/go-deps/vendor/github.com/99designs/gqlgen

The branch I'm working on is available here: https://gitlab.com/the.nasso/daily-digest/tree/go-deps

Do the contents of `vendor/github.com/99designs/gqlgen` look like they should?

**Comment by vektah** [comment]
You either need to adjust your [prune settings](https://golang.github.io/dep/docs/Gopkg.toml.html#prune) so dep doesn't remove the main package, or add `required = ["github.com/99designs/gqlgen"]` in your Gopkg.toml to let dep know its being used.

**Comment by JulienBreux** [comment]
@vektah thanks for the tips. Very useful for others!

**Comment by emil-nasso** [comment]
Sorry about the late response. I can't seem to nail this...

I have removed all prune settings from the gopkg-file and added the `required`.

My `gopkg.toml` looks like this:

```toml
# Gopkg.toml example

required = ["github.com/99designs/gqlgen"]

[[constraint]]
  name = "github.com/99designs/gqlgen"
  version = "0.6.0"

[[constraint]]
  name = "github.com/davecgh/go-spew"
  version = "1.1.1"

[[constraint]]
  name = "github.com/mmcdole/gofeed"
  version = "1.0.0-beta2"

[[constraint]]
  name = "github.com/gofrs/uuid"
  version = "3.1.1"

[[constraint]]
  branch = "master"
  name = "github.com/vektah/gqlparser"
```

When i build it i run this:

```bash
go get -u github.com/vektah/gorunpkg
curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
dep ensure
go generate ./...
```

When this is built i get the following error:

```
go generate ./...
pkg: cannot find package "github.com/99designs/gqlgen" in any of:
	/usr/local/go/src/github.com/99designs/gqlgen (from $GOROOT)
	/go/src/github.com/99designs/gqlgen (from $GOPATH)
server/app.go:1: running "gorunpkg": exit status 1
```

It's not even looking in the vendor directory.

What am I doing wrong?

The complete code can be found here: 
https://gitlab.com/the.nasso/daily-digest/tree/go-deps

I'm looking forward until the day that I can completely move away from the shared workspace in go. ;)
