### ISSUE TITLE
Change default file names?

### ISSUE THREAD

**Issue by frederikhors** [99designs/gqlgen#421]
Can I propose these default file names?

```yml
exec:
  filename: generated.go # (or generated_engine.go or generated_exec.go)

model:
  filename: generated_models.go

resolver:
  filename: generated_resolvers.go
```
