### ISSUE TITLE
Getting started: "exec plan failed: unable to resolve package..."

### ISSUE THREAD

**Issue by teeler** [99designs/gqlgen#474]
### Minimal graphql.schema and models to reproduce
```shell
{•̃_•̃} ls -alh
total 56
drwxr-xr-x  12 rtp  primarygroup   384B Dec 15 19:27 .
drwxr-xr-x   6 rtp  primarygroup   192B Dec 15 19:18 ..
-rw-r--r--   1 rtp  primarygroup   3.0K Dec 15 19:26 Gopkg.lock
-rw-r--r--   1 rtp  primarygroup   730B Dec 15 19:18 Gopkg.toml
-rw-r--r--   1 rtp  primarygroup   323B Dec 15 19:19 gqlgen.yml
-rw-r--r--   1 rtp  primarygroup   244B Dec 15 19:27 models_gen.go
-rw-r--r--   1 rtp  primarygroup   520B Dec 15 19:19 resolver.go
-rw-r--r--   1 rtp  primarygroup   255B Dec 15 19:18 schema.graphql
drwxr-xr-x   3 rtp  primarygroup    96B Dec 15 19:18 scripts
drwxr-xr-x   3 rtp  primarygroup    96B Dec 15 19:19 server
-rw-r--r--   1 rtp  primarygroup   103B Dec 15 19:19 todo.go
drwxr-xr-x   5 rtp  primarygroup   160B Dec 15 19:26 vendor
```

Files are as desired in https://gqlgen.com/getting-started/

gqlgen.go:
```yaml
# .gqlgen.yml example
#
# Refer to https://gqlgen.com/config/
# for detailed .gqlgen.yml documentation.

schema:
- schema.graphql
exec:
  filename: generated.go
model:
  filename: models_gen.go
resolver:
  filename: resolver.go
  type: Resolver
models:
  Todo:
    model: github.com/teeler/gqlgen-todos/gettingstarted.Todo
```

todo.go:
```go
package gettingstarted

type Todo struct {
	ID     string
	Text   string
	Done   bool
	UserID string
}

```

Output:
```shell
{•̃_•̃} go run scripts/gqlgen.go -v
exec plan failed: unable to resolve package for github.com/teeler/gqlgen-todos/gettingstarted.Todo: cannot find package "github.com/teeler/gqlgen-todos/gettingstarted" in any of:
	/Users/rtp/go/src/github.com/teeler/gqlgen-todos/vendor/github.com/teeler/gqlgen-todos/gettingstarted (vendor tree)
	/usr/local/go/src/github.com/teeler/gqlgen-todos/gettingstarted (from $GOROOT)
	/Users/rtp/go/src/github.com/teeler/gqlgen-todos/gettingstarted (from $GOPATH)

exit status 2

```

**Comment by rlouapre** [comment]
Try to rename `todo.go` in `gettingstarted/gettingstarted.go`

**Comment by Oxyrus** [comment]
I'm actually having similar issues while following the [getting started](https://gqlgen.com/getting-started/) and using the [todo example](https://github.com/99designs/gqlgen/tree/master/example/todo) as a guideline.

My folder structure is as follows:

```
gettingstarted/
  todo.go
scripts/
server/
vendor/
generated.go
Gopkg.lock
Gopkg.toml
gqlgen.yml
models_gen.go
resolver.go
schema.graphql
```

```go
// gettingstarted/todo.go
package gettingstarted

type Todo struct {
	ID     string
	Text   string
	Done   bool
	UserID string
}
```

```yaml
# gqlgen.yml
models:
  Todo:
    model: github.com/Oxyrus/gqlgen-todos/gettingstarted.Todo
```

However, when I run `$ go run scripts/gqlgen.go -v`, I get the following error:

> Unable to bind Todo.user to github.com/Oxyrus/gqlgen-todos/gettingstarted.Todo
>   no method named user
>   no field named user
>   Adding resolver method
> C:\Users\USUARIO\go\src\github.com\Oxyrus\gqlgen-todos\resolver.go:18:76: undeclared name: Todo
> C:\Users\USUARIO\go\src\github.com\Oxyrus\gqlgen-todos\resolver.go:24:55: undeclared name: Todo
> C:\Users\USUARIO\go\src\github.com\Oxyrus\gqlgen-todos\resolver.go:13:9: cannot use &(queryResolver literal) (value of type *queryResolver) as QueryResolver value in return statement: wrong type for method Todos
> C:\Users\USUARIO\go\src\github.com\Oxyrus\gqlgen-todos\resolver.go:10:9: cannot use &(mutationResolver literal) (value of type *mutationResolver) as MutationResolver value in return statement: wrong type for method CreateTodo
> validation failed: couldn't load packages due to errors: github.com/Oxyrus/gqlgen-todos
> exit status 2

I don't know if that's the output I'm looking for, considering the getting started page only contains the following:

> $ go run scripts/gqlgen.go -v
> Unable to bind Todo.user to github.com/[username]/gqlgen-todos/gettingstarted.Todo
> 	no method named user
> 	no field named user
> 	Adding resolver method
