### ISSUE TITLE
missing package name on generated resolver code

### ISSUE THREAD

**Issue by mia0x75** [99designs/gqlgen#507]
### Expected Behaviour
```
type Resolver struct{}

func (r *Resolver) Mutation() gqapi.MutationResolver {
	return &mutationResolver{r}
}
func (r *Resolver) Query() gqapi.QueryResolver {
	return &queryResolver{r}
}
```

### Actual Behavior
```
type Resolver struct{}

func (r *Resolver) Mutation() MutationResolver {
	return &mutationResolver{r}
}
func (r *Resolver) Query() QueryResolver {
	return &queryResolver{r}
}
```

### Minimal graphql.schema and models to reproduce
```
schema:
- queries/schema.graphql

exec:
  filename: gqapi/generated.go
  package: gqapi # missing Config.Exec.Package for resolver.go

model:
  filename: gqapi/models.go
  package: gqapi

resolver:
  filename: resolvers/resolver.go
  package: resolvers
  type: Resolver
```
