### ISSUE TITLE
model from submodule is not resolved during codegen

### ISSUE THREAD

**Issue by ermik** [99designs/gqlgen#521]
### Expected Behaviour
`go generate` via script would run after conversion to go modules
### Actual Behavior
I'm getting `modelgen: unable to find type` with type referencing `gqlgen.yaml` directive to look for one of the types in a submodule.

Here's the project structure:
```
gqlgen.yaml
scripts/ — (gqlgen script is here)
src/ — (root module, the project)
    gqlgen/  — (module)
        models.go — (model)
        graphql.go — (exec)
    pkg/
        transport/ — (submodule)
            graphql.go — (resolver with go generate)
        endpoint/ — (submodule)
            sometype.go — (referenced type is here)
        ...  
```
so `gqlgen.yaml` is something along the lines of:
```yaml
schema: src/gqlgen/schema.graphql
exec:
  filename: src/gqlgen/graphql.go
model:
  filename: src/gqlgen/models.go
struct_tag: json
models:
  SomeType:
    model: domain.com/projectname/pkg/endpoint.SomeType
resolver:
  filename: src/pkg/transport/graphql.go
  type: Resolver

```
while `go.mod` in `domain.com/project/gqlgen` module will have to say:
```go
require (
	domain.com/projectname/pkg/endpoint v0.0.0
	// and dependencies of the endpoint module
)

replace (
	domain.com/projectname/pkg/endpoint => ../pkg/endpoint
	// and dependencies of the endpoint module
)
```

The local (there is no `https://` repo) `pkg` modules are specified explicitly via `require` & `replace` directives. `src` directory is not part of module names, but the project builds fine with old gqlgen code (`go build` finds everything just fine). `go generate` shows network `go get`'s, so I'm not sure if this is a gqlgen or go problem.
