### ISSUE TITLE
Issue when Generated Models Target Path Missing

### ISSUE THREAD

**Issue by mathewbyrne** [99designs/gqlgen#564]
### Expected Behaviour

When targeting a non-existent path for model gen, a couple of issues arise:

1. `Package` does not correctly default to the last part of the path, which causes a panic in codegen.

2. Even if package is specified, it still fails (no panic) with error:
  ```
  merging failed: unable to build object definition: missing package name for <model>
  ```

### Actual Behavior

I would expect that I do not need to define a package name explicitly, and for there to be no further errors.

Some initial debugging had us looking at https://github.com/99designs/gqlgen/blob/next/internal/code/imports.go#L21-L23 as a potential culprit and where the fix should be.

### Minimal graphql.schema and models to reproduce

```
schema:
- schema.graphql
exec:
  filename: graph/generated.go
model:
  filename: models/generated.go
resolver:
  filename: graph/resolver.go
  type: Resolver
```

Ensure that the `models` directory does not exist.
