### ISSUE TITLE
Allow field resolvers on interface types

### ISSUE THREAD

**Issue by jszwedko** [99designs/gqlgen#592]
### Expected Behaviour

I'd like to be able to specify that a field resolver should be generated on a GraphQL `interface` type.

The purpose of this is to reduce duplication of code for resolved fields that are resolved in the same way for all types implementing the interface.

If possible, it could look for a field resolver on the concrete type, and, if it finds none, fall back to the resolver on the interface type to allow overriding it in the cases where you might want to. For my particular use case, I have no need to override the field resolver on the interface type as they are all resolved in the same way for all implementations.

### Actual Behavior

Right now, I have to specify that a resolver should be generated on the fields of each GraphQL `type` implementing the interface. This results in some duplication as, in my case, the shared fields are all resolved in the same fashion.

### Minimal graphql.schema and models to reproduce

This is a simplified use case of ours (we have types modeling data sources that all share some configuration).

`schema.graphql`
```graphql
interface Shape {
  id: ID!
  name: String!
}

type Rectangle implements Shape {
  id: ID!
  name: String!

  square: Boolean!
}

type Circle implements Shape {
  id: ID!
  name: String!
}

type Query {
  shapes: [Shape]
}
```

gqlgen.yml
```yml
# .gqlgen.yml example
#
# Refer to https://gqlgen.com/config/
# for detailed .gqlgen.yml documentation.

schema:
- schema.graphql
exec:
  filename: generated.go
model:
  filename: models_gen.go
resolver:
  filename: resolver.go
  type: Resolver

models:
  Shape:
    fields:
      id:
        resolver: true
      name:
        resolver: true
```

resolver.go generated
```
codegen/config/config.go
