### ISSUE TITLE
[0.8.1] Default scalar models not generated

### ISSUE THREAD

**Issue by jszwedko** [99designs/gqlgen#593]
### Expected Behaviour

A default string implementation of the scalar is generated.

### Actual Behavior

No default model for scalars is generated.

In `v0.7.1`, scalars without a model specified in `gqlgen.yml` would be replaced by `*string` in the generated models.

In `v0.8.1`, the scalar type is included in the generated code as the type for struct fields, but with no implementation.

#588 references fixing this issue, but the configuration below doesn't generate the default scalar implementation as I expected.

### Minimal graphql.schema and models to reproduce

schema.graphql
```graphql
scalar Foo

type Bar {
  foo: Foo
}

type Query {
  bars: [Bar]
}
```

gqlgen.yml
```yaml
# .gqlgen.yml example
#
# Refer to https://gqlgen.com/config/
# for detailed .gqlgen.yml documentation.

schema:
- schema.graphql
exec:
  filename: generated.go
model:
  filename: models_gen.go
resolver:
  filename: resolver.go
  type: Resolver
```

Generated models:

```go
// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package test_gqlgen

type Bar struct {
	Foo *Foo `json:"foo"`
}
```

Note that no `Foo` is generated.

In 0.7.1, the generated model looks like:

```go
// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package test_gqlgen

type Bar struct {
        Foo *string `json:"foo"`
}
```

I've worked around this by specifying:

```yaml
models:
  Foo:
    model: github.com/99designs/gqlgen/graphql.String
```

in gqlgen.yml
