### ISSUE TITLE
Provide a configuration option to generate embedded types

### ISSUE THREAD

**Issue by steebchen** [99designs/gqlgen#626]
This schema

```graphql
interface User {
	id: ID!
	email: String!
}

type Customer implements User {
	id: ID!
	email: String!

	favoriteEmployee: Employee
}

type Employee implements User {
	id: ID!
	email: String!

	favoriteCustomers: [Customer!]!
}
```

produces

```go
type User interface {
	IsUser()
}

type Customer struct {
	ID               string    `json:"id"`
	Email            string    `json:"email"`
	FavoriteEmployee *Employee `json:"favoriteEmployee"`
}

func (Customer) IsUser() {}

type Employee struct {
	ID                string     `json:"id"`
	Email             string     `json:"email"`
	FavoriteCustomers []Customer `json:"favoriteCustomers"`
}

func (Employee) IsUser() {}
```

This works fine, but it's cumbersome to work with when converting from an internal type (e.g. `User`) to a `Customer` or `Employee`.

This forces me to declare those types by myself and import them in gqlgen:

```go
type User struct { // my original user type
	ID     string `json:"id"`
	Email  string `json:"email"`
}

func (User) IsUser() {}

type Customer struct {
	*User
	favoriteEmployee *Employee
}

type Employee struct {
	*User
	favoriteCustomers []Customer
}
```

```yaml
# ...
models:
  User:
    model: github.com/steebchen/api/prisma.User
  Customer:
    model: github.com/steebchen/api/prisma.Customer
  Employee:
    model: github.com/steebchen/api/prisma.Employee
```

This also works fine, but it's a bit annoying to define it manually and importing it manually. It also gets more cumbersome if the schema gets more complex with more user types and more complex schemas (for example when implementing multiple interfaces).

It would be great if there was an option so that embedded structs could be automatically generated.

**Comment by mathewbyrne** [comment]
Do you have any thoughts on what the configuration for this would look like?

**Comment by steebchen** [comment]
Not quite sure what would be best, I'll just throw some suggestions

What about a simple `embedded_types: true` globally?

That could be maybe too restrictive, so maybe a completely dedicated option for interfaces:

```yaml
embedded:
  - Customer
  - Employee
```

or maybe in the top-level object:

```yaml
models:
  User:
    model: github.com/steebchen/keskin-api/prisma.User
    embed:
      - Customer
      - Employee
```

or separately and specify a type to embed:

```yaml
models:
  Customer:
    embedded: true
    # or more explicitly
    embed: github.com/steebchen/keskin-api/prisma.User
    # this should mean generate the model but embed `User`
```

**Comment by vektah** [comment]
An alternative approach would be something like:
```yaml
  User:
    embed: github.com/steebchen/keskin-api/prisma.User
    interface: github.com/steebchen/keskin-api/prisma.IUser 
```
note config modelgen currently injects into config before generating is
```yaml
  User:
    model: github.com/steebchen/keskin-api/prisma.IUser 
```

Anything implementing the interface would automatically embed the given type, if one is set. 

Multiple inheritance is a thing too, [eg from the spec](https://facebook.github.io/graphql/June2018/#example-ab5e5)
```graphql
interface NamedEntity {
  name: Stringneed to 
}

interface ValuedEntity {
  value: Int
}

type Person implements NamedEntity {
  name: String
  age: Int
}

type Business implements NamedEntity & ValuedEntity {
  name: String
  value: Int
  employeeCount: Int
}
```

could generate 
```go
type INamedEntity interface {
    IsINamedEntity()
}
type NamedEntityBase struct {
    Name string
}

func (NamedEntityBase) IsINamedEntity() {}

type IValuedEntity interface {
    IsIValuedEntity()
}

type ValuedEntityBase struct {
    Value string
}

func (ValuedEntityBase) IsIValuedEntity() {}

type Person struct {
  *NamedEntityBase
   Age int
}

type Business struct {
  *NamedEntityBase
  *ValuedEntityBase
   EmployeeCount int
}
```

@lwc implemented the current interface generation, I wonder if he has thoughts?
