### ISSUE TITLE
Fails to generate valid source

### ISSUE THREAD

**Issue by akabos** [99designs/gqlgen#627]
### Expected Behaviour

`go run github.com/99designs/gqlgen -v` generates valid Go source.

### Actual Behavior

`go run github.com/99designs/gqlgen -v` throws:

```
gofmt failed on generated.go: .../generated.go:299:24: expected ')', found ',' (and 1 more errors)
```

Line 299 of `generated.go` reads:

```
				arg0, err = ec.(ctx, tmp)
```

### Minimal graphql.schema and models to reproduce

```
type SomeMutationInput {
    somefield: String!
}

type SomeMutationResult {
    somefield: String!
}

type Query {
    someQuery: [String!]!
}

type Mutation {
    someMutation(input: SomeMutationInput!): SomeMutationResult!
}
```

```
schema:
  - schema.graphql
exec:
  filename: generated.go
model:
  filename: models_gen.go
resolver:
  filename: resolver.go
  type: Resolver
```

My first impression was the bug was platform or Go version dependent, so I tried with following OS/sersion combinations. Results are identical.
 
* `go1.12.1 darwin/amd64`  
* `go1.11.6 darwin/amd64`
* `go1.12.1 linux/amd64`
* `go1.11.6 linux/amd64`
