### ISSUE TITLE
Race condition setting invalid in generated code

### ISSUE THREAD

**Issue by aduong** [99designs/gqlgen#699]
### What happened?

Running a server with the race detector involved detected a race condition. Generated code that runs concurrently can attempt to set the `invalid` variable to true.

The generated code:

```go
	out := graphql.NewFieldSet(fields)
	invalid := false
	for i, field := range fields {
		switch field.Name {
		// ...
		case "foo":
			field := field
			out.Concurrently(i, func() (res graphql.Marshaler) {
				// ...
				res = ec._Bazz_foo(ctx, field, obj)
				if res == graphql.Null {
					invalid = true
				}
				// ...
		case "bar":
			field := field
			out.Concurrently(i, func() (res graphql.Marshaler) {
				// ...
				res = ec._Bazz_bar(ctx, field, obj)
				if res == graphql.Null {
					invalid = true
				}
				// ...
	// ...
	out.Dispatch()
```

which will yield logs like

```
WARNING: DATA RACE
Write at ... by goroutine ...:
...
Previous write at ... by goroutine ...:
```

### Minimal graphql.schema and models to reproduce

```graphql
type Query {
  bazz(id: String!): Bazz!
}

type Bazz {
  foo: String!
  bar: String!
}
```

```yaml
# gqlgen.yml
schema:
- schema.graphql
exec:
  filename: generated.go
model:
  filename: models_gen.go
resolver:
  filename: resolver.go
  type: Resolver
models:
  Bazz:
    model: github.com/aduong/go-test/gql.Bazz
```

```go
// bazz.go
package gql

import "context"

type Bazz struct {}

func (u Bazz) Foo(ctx context.Context) string {
	panic(nil)
}

func (u Bazz) Bar(ctx context.Context) string {
	panic(nil)
}
```

### versions
 - `gqlgen version`? v0.8.3
 - `go version`? go1.12 linux/amd64
 - dep or go modules? go modules
