### ISSUE TITLE
ID! type in schema mapping to `string` type in generated model, not external.ObjectID

### ISSUE THREAD

**Issue by debnath** [99designs/gqlgen#712]
### What happened?
I specified type `ID!` in the graphql schema, and the generated models was a `string`.

e.g.

schema: 
```
type CustomThing implements Something & SomethingElse {
  id: ID!
}
```

generated model:
```
type CustomThing struct {
	ID      string `json:"id"`
}
```

### What did you expect?
My schema talks to 2 different APIs, one where the ID is an integer, and the other the ID is a string.  I expected that specifying `ID!` in the schema would result in the generated models be a custom type (e.g. `interface{}`).

Looking at the scalar example, the `ID!` schema specification maps to ` external.ObjectID` in the generated struct, which I assume handles string and int.
https://github.com/99designs/gqlgen/blob/master/example/scalars/model/model.go

### Minimal graphql.schema and models to reproduce

Graphql schema: 
```
type TestThing {
  id: ID!
}
```
Run `go run github.com/99designs/gqlgen` and look at the generated struct.

### versions
 - `gqlgen version`?  dev
 - `go version`? go version go1.12.1 darwin/amd64
 - dep or go modules? dep

**Comment by lwc** [comment]
GraphQL types can be bound to multiple go types, from the configuration section of the docs:
```
models:
  ID: # graphql type
    model:
      - github.com/99designs/gqlgen/graphql.IntID # go type
      - github.com/99designs/gqlgen/graphql.ID     # other go type
```

You can use something like this to bind to each of your two underlying ID types
