### ISSUE TITLE
Generated models do not implement user defined interfaces

### ISSUE THREAD

**Issue by samlitowitz** [99designs/gqlgen#716]
### What happened?
Generated models do not fulfill user defined interfaces provided through models configuration.
```go
// models/generated.go
// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type MyObect struct {
	ID string `json:"id"`
}

func (MyObect) IsMyInterface() {}
```

### What did you expect?
An error preventing me from doing this, OR the generated models need to fulfill the user defined interface, i.e.
```go
// models/generated.go
// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type MyObect struct {
	ID string `json:"id"`
}

func (MyObect) Baz() {}
```

### Minimal graphql.schema and models to reproduce
```yml
# .gqlgen.yml
exec:
  filename: generated/exec.go
model:
  filename: models/generated.go

models:
  MyInterface:
    model: github.com/99designs/gqlgen/example/interface_failure/models.MyInterface

```
```graphql
# schema.graphql
interface MyInterface  {
    id: ID!
}

type MyObect implements MyInterface {
    id: ID!
}

type Query {
    myObjects: MyObect!
}
```
```go
// models/my_interface.go
package models

type MyInterface interface {
	Baz()
}
```

### versions
 - `gqlgen version`? `dev`,  from master with test case added to the `example/` directory
 - `go version`? `go version go1.12.4 linux/amd64`
 - dep or go modules? master branch [go.mod](https://github.com/99designs/gqlgen/blob/master/go.mod)
