### ISSUE TITLE
The resolvergen and servergen plugins do not fully support a configured resolver type.

### ISSUE THREAD

**Issue by seriousben** [99designs/gqlgen#747]
### What happened?

Generated code does not compile.

### What did you expect?

Generated code to compile.

### Minimal graphql.schema and models to reproduce

gqlgen.yml:

```
schema:
- schema.graphql
exec:
  filename: generated.go
model:
  filename: models_gen.go
resolver:
  filename: resolver.go
  type: ResolverRoot
```
