### ISSUE TITLE
Handling opaque types transparently

### ISSUE THREAD

**Issue by jszwedko** [99designs/gqlgen#775]
### What happened?

I was hoping that gqlgen would transparently handle an opaque slice type:

```golang
type StringSlice []string
```

Which I am using in my models to have them deserialize from a PostgreSQL array column. For example:

```golang
type Todo struct {
  tags StringSlice
}
```

With a schema of:

```graphql
type Todo {
  tags: [String!]!
}

type Query {
  todos: [Todo!]!
}
```

However, gqlgen expects a resolver to be generated for this even though the it could transparently handle marshaling and unmarshaling as it supports doing so with the underlying `[]string`.

It appears opaque string types are specifically handed to avoid needing to defining marshal and unmarshal methods:

https://github.com/99designs/gqlgen/blob/414a4d3414b2b5856851816f0152980098f7b3ab/codegen/config/binder.go#L364-L377

So there is some precedence.

I poked around trying to add this to the binder, but couldn't get it working quite right. I figured I'd open this issue at least to track and see if this would be helpful to others.

### What did you expect?

gqlgen would generate resolvers to marshal and unmarshal from the `StringSlice`.

### Minimal graphql.schema and models to reproduce

```graphql
type Todo {
  tags: [String!]!
}

type Query {
  todos: [Todo!]!
}
```

```golang
type Todo {
  tags: [String!]!
}

type Query {
  todos: [Todo!]!
}
```

```yml
schema:
- schema.graphql
exec:
  filename: generated.go
model:
  filename: models_gen.go
resolver:
  filename: resolver.go
  type: Resolver
autobind: []
models:
  Todo:
    model: github.com/jszwedko/test-gqlgen.Todo

```

### versions
 - `gqlgen version 0.9.1`
 - `go version 12.6.1`
