### ISSUE TITLE
Allow specifying a path prefix for models

### ISSUE THREAD

**Issue by leebenson** [99designs/gqlgen#778]
**Proposal:**

`autobind` is a great addition, but I have models that don't always match the type name 1:1.

It'd be useful to augment autobind with a path prefix, which could then be used as a starting point to find a model using the regular `<package>.<model>` designation, e.g.

```yml
autobind:
  - github.com/some/custom/pkg/path/here

models:
  SomeCustomType:
    model: somePackage.CustomType
```

Ultimately, my goal is to move this config to schema files and avoid hard-coding absolute package paths for each definition / repeating the same prefix:

```gql
type SomeCustomType @goModel(model:"somePackage.CustomType") {
  ...
}
```
