### ISSUE TITLE
Using directives on a field returning an interface does not allow `nil`

### ISSUE THREAD

**Issue by jszwedko** [99designs/gqlgen#799]
### What happened?

Using a directive on a field that returns a GraphQL/Go `interface` type prohibits you from returning `nil`, even if the field is nullable,  as the generated type assertion fails.

### What did you expect?

Returning `nil` for an interface field that is nullable is possible when using a directive.

### Minimal graphql.schema and models to reproduce

schema.graphql

```graphql
directive @user on FIELD_DEFINITION

interface Node {
  id: ID!
}

type Query {
  node(id: ID!): Node @user
}
```

gqlgen.yml

```yml
# .gqlgen.yml example
#
# Refer to https://gqlgen.com/config/
# for detailed .gqlgen.yml documentation.

schema:
- schema.graphql
exec:
  filename: generated.go
model:
  filename: models_gen.go
resolver:
  filename: resolver.go
  type: Resolver
autobind: []
```

resolver.go

```go
package gqlgen_test

import (
        "context"
)

type Resolver struct{}

func (r *Resolver) Query() QueryResolver {
        return &queryResolver{r}
}

type queryResolver struct{ *Resolver }

func (r *queryResolver) Node(ctx context.Context, s string) (Node, error) {
        return nil, nil
}

type Node interface {
        IsNode()
}
```

The issue appears to be with this part of the generated code:

```go
  resTmp, err := ec.ResolverMiddleware(ctx, func(rctx context.Context) (interface{}, error) {
    directive0 := func(rctx context.Context) (interface{}, error) {
      ctx = rctx // use context from middleware stack in children
      return ec.resolvers.Query().Node(rctx, args["id"].(string))
    }
    directive1 := func(ctx context.Context) (interface{}, error) {
      return ec.directives.User(ctx, nil, directive0)
    }
    tmp, err := directive1(rctx)
    if err != nil {
      return nil, err
    }
    if data, ok := tmp.(Node); ok {
      return data, nil
    }
    return nil, fmt.Errorf(`unexpected type %T from directive, should be gqlgen-test.Node`, tmp)
  })
```

I believe it should check for `nil` before the type assertion check as type assertions will return false if the stored value is `nil`.

### versions

```
module gqlgen-test

go 1.12

require (
        github.com/99designs/gqlgen v0.9.1
        github.com/vektah/gqlparser v1.1.2
)
```
