### ISSUE TITLE
How to pass the parameters of the previous Resolver to the next Resolver

### ISSUE THREAD

**Issue by huanghantao** [99designs/gqlgen#813]
### What happened?
I have two Resolvers now, The corresponding gqlgen.yml is as follows:
```yml
Server:
    fields:
      serverLogs:
        resolver: true # force a resolver to be generated
```
Resolvers is as follows:
the first resolver:
```go
func (r *queryResolver) OneServer(ctx context.Context, ip *string, domainName *string) (*genmodel.Server, error)
```
the next resolver:
```go
func (r *serverResolver) ServerLogs(ctx context.Context, obj *genmodel.Server, startTime *int, endTime *int, serverLogTypeInput []genmodel.ServerLogType, logConnectionInput *genmodel.ConnectionInput) (*genmodel.ServerLogConnection, error)
```
How can I get the parameter ip and domainName  in OneServer from ServerLogs?
### versions
 - `gqlgen version`? 
 - `go version`?
 - dep or go modules?
