### ISSUE TITLE
scalar Time produces errors in generated.go

### ISSUE THREAD

**Issue by RobinKamps** [99designs/gqlgen#891]
### What happened?
Generate Output has errors on Win 10

time and time.Time resolve to "invalid type"

perhaps due to the usage of ᚐ as a replacement for . ?

```
 res := resTmp.(invalid type)   //should be a type timeᚐTime not "invalid type"

func ...
ec.marshalNTime2invalid type //should be of type timeᚐTime as well

```

### What did you expect?
No bug when using Time

### Minimal graphql.schema and models to reproduce

```
type Query {
    customers: [Customer!]

    # these methods are here to test code generation of nested arrays
    torture1d(customerIds: [Int!]): [Customer!]
    torture2d(customerIds: [[Int!]]): [[Customer!]]
}

type Customer {
    id: Int!
    name: String!
    address: Address
    orders: [Order!]
}

type Address {
    id: Int!
    street: String!
    country: String!
}

type Order {
    id: Int!
    date: Time!
    amount: Float!
    items: [Item!]
}

type Item {
    name: String!
}

scalar Time
```

yml
```
schema:
- schema.graphql
exec:
  filename: generated.go
model:
  filename: models_gen.go
resolver:
  filename: resolver.go
  type: Resolver
autobind: []
````

### versions
 - `gqlgen version`?  latest
 - `go version`? 1.13
 - dep or go modules? modules
