### ISSUE TITLE
gqlgen Autobind internal package - unable to find type

### ISSUE THREAD

**Issue by ihgann** [99designs/gqlgen#911]
### What happened?

Tried to resolve an autobind in an internal path:

```yaml
autobind:
  - github.com/ihgann/app/internal/models
models:
  Todo:
    model: models.Todo
```

```
> go run github.com/99designs/gqlgen -v
panic: unable to find type models.Todo
```

### What did you expect?

It should still be able to find the path.

### Minimal graphql.schema and models to reproduce

From examples.

### versions
 - `gqlgen version`? v0.10.1
 - `go version`? 1.12.9 darwin/amd64
 - dep or go modules? go modules

---

A note. I don't know if this is necessarily expected to work, as I'm unsure how `gqlgen` is actually determining packages. If it only works with exported packages, then I suppose this makes sense. However, perhaps it should be documented?
