### ISSUE TITLE
Custom Scalar / Marshaler throws errors in generated code

### ISSUE THREAD

**Issue by gigo1980** [99designs/gqlgen#980]
### What happened?
I have written a marshaler for some DateTypes to be ISO8601 conform.
This is the code of the marshaler
https://gist.github.com/gigo1980/e77549d19aa807b5e3bfc84762049cf9

If I try to run my application, I get an error from the generated code.
```
internal/app/graphql/gql_exec_gen.go:4091:2: not enough arguments to return
internal/app/graphql/gql_exec_gen.go:4091:11: ec.unmarshalInputDateTime undefined (type *executionContext has no field or method unmarshalInputDateTime)
internal/app/graphql/gql_exec_gen.go:4095:11: ec._DateTime undefined (type *executionContext has no field or method _DateTime)
internal/app/graphql/gql_exec_gen.go:4469:2: not enough arguments to return
internal/app/graphql/gql_exec_gen.go:4469:11: ec.unmarshalInputDate undefined (type *executionContext has no field or method unmarshalInputDate)
internal/app/graphql/gql_exec_gen.go:4473:11: ec._Date undefined (type *executionContext has no field or method _Date)
internal/app/graphql/gql_exec_gen.go:4488:11: ec._Date undefined (type *executionContext has no field or method _Date)
```
I have created the marshaler as described here https://gqlgen.com/reference/scalars/

### What did you expect?

The application should start and does not throw this error

### Minimal graphql.schema and models to reproduce
```
# This file was generated based on "person.json". Do not edit manually.

schema {
    query: Query
    mutation: Mutation
}

type Mutation {
    createPerson(input: NewPerson): Person
    deletePerson(identifier: ID!): Boolean
}

type Person {
    active: Boolean!
    birthDate: Date
    createdAt: DateTime!
    description: String
    identifier: ID!
    updatedAt: DateTime!
}

type Query {
    person(identifier: ID!): Person
    persons(): [Person!]!
}


input NewPerson {
    birthDate: Date
}

"DateTime in ISO8601, e.g. 2006-01-31T15:04:05-07:00"
scalar DateTime

"Date in ISO8601 e.g. 2006-01-31"
scalar Date

"Time in ISO8601, e.g. 15:04:05-07:00"
scalar Time
```
### versions
 - `gqlgen version` 0.10.2
 - `go version` 1.13.4

**Comment by lwc** [comment]
Looks like a MashalTime in that source - oops! 😅

Also are you binding the types in either the schema or gqlgen.yml?

**Comment by gigo1980** [comment]
I can remove that MarshalTime. I know that there is already an existing Scalar Type for Time.

```yaml
models:
  ID:
    model: github.com/***/util-graphql/pkg/scalars/model.ID
  DateTime:
    model: github.com/***/util-graphql/pkg/scalars/model.DateTime
  Date:
    model: github.com/***/util-graphql/pkg/scalars/model.Date
  Time:
    model: github.com/***/util-graphql/pkg/scalars/model.Time

```
